### ISSUE TITLE
Add support for opening any `https://mail.google.com/mail/u/0/#...` URL

### ISSUE THREAD

**Issue by cipriancraciun** [timche/gmail-desktop#101]
One nice feature of GMail is that most of the views generate a unique URL like `https://mail.google.com/mail/u/0/#...` that when opened in a new window (in a browser where you are authenticated) it opens exactly the same view.  For example: `https://mail.google.com/mail/u/0/#search/from%3Asomeone%40example.com` will open the search view with `from:someone@example.com`.

It would be nice to be able to say `gmail-desktop 'https://mail.google.com/mail/u/0/#search/from%3Asomeone%40example.com'` and open exactly the same view, which is as simple as opening a new page with that URL.

---

This goes hand-in-hand with #90 (the one about saved searches).

**Comment by timche** [comment]
Closing this issue due to lack of interest and/or inactivity.
