### ISSUE TITLE
Add support for a compose spell-checker

### ISSUE THREAD

**Issue by cipriancraciun** [timche/gmail-desktop#102]
One extra missing (but extremely useful) functionality is the spell-checker for the compose window.

**Comment by timche** [comment]
Doesn't Gmail already has a spell-checking?

![image](https://user-images.githubusercontent.com/8075074/56653132-e67a4600-6684-11e9-95e0-fa371503c753.png)

**Comment by timche** [comment]
Anyway, we can opt-in to use our own: https://github.com/electron-userland/electron-spellchecker

**Comment by cipriancraciun** [comment]
> Doesn't Gmail already has a spell-checking?

Apparently it does -- I never knew about it...  However I always used the "inline" spell-checker provided by the browser which underlines misspelled words in real-time.

Therefore perhaps this feature isn't that important (although it would be a nice-to-have feature).

**Comment by timche** [comment]
This is actually not easy to implement. [`electron-spellchecker`](`https://github.com/electron-userland/electron-spellchecker/`) comes with it's own context menu and we are using [`electron-context-menu`](https://github.com/sindresorhus/electron-context-menu) for our context menu. I tried implementing both, but without success yet.

**Comment by cipriancraciun** [comment]
@timche In the end if GMail has support for this builtin it's not an issue...

(Perhaps you could create a new tag, something like `nice-to-have`, tag this issue, and then close it.  Then sometime later if there is time left someone could tackle this...)

**Comment by timche** [comment]
Closing in favour of Gmail's built-in spell checker:

<img width="279" alt="Screenshot 2019-12-19 at 14 14 19" src="https://user-images.githubusercontent.com/8075074/71176317-e2311780-2269-11ea-8e05-2042d5ac3cc8.png">
