### ISSUE TITLE
Option to change default notification sound

### ISSUE THREAD

**Issue by timche** [timche/gmail-desktop#110]
Replace with something from: https://freesound.org

Keywords:
- alert
- notification
- bell

**Comment by markypython** [comment]
@timche Why would we want to add this to the app?

**Comment by timche** [comment]
Because right now it plays the default OS alert, doesn't it? Thought of giving the app it's own style.

**Comment by markypython** [comment]
I would leave this to individual users as they can configure their notification sound in system preferences.

**Comment by markypython** [comment]
@timche Thoughts on this?

**Comment by arlogilbert** [comment]
> I would leave this to individual users as they can configure their notification sound in system preferences.

At least on Mac OSX there is no ability to customize notification sounds at the OS level per app. There is just the "sound" that is the default and it's pretty weird for a mail sound.

**Comment by markypython** [comment]
@arlogilbert At the least it should be a configuration option so that users can leave it as the default notification sound.

**Comment by timche** [comment]
I'm still up for making this configurable, but also changing the default would give this app some more unique character.
