### ISSUE TITLE
Download notifications

### ISSUE THREAD

**Issue by markypython** [timche/gmail-desktop#115]
With the new download experience, there is no user feedback when the download is done aside from the fact that the progress bar is gone.  For small downloads, this is difficult to see as it comes and goes really quickly.

Thoughts on adding a notification when the download is complete?

**Comment by timche** [comment]
Sure. I'd like to see it added as optional setting. `electron-dl` provides a callback [`onProgress`](https://github.com/sindresorhus/electron-dl#onprogress).

**Comment by timche** [comment]
This can be extended to make the downloading even more configurable as `electron-dl` provides more functions like [`openFolderWhenDone`](https://github.com/sindresorhus/electron-dl#openfolderwhendone), [`directory`](https://github.com/sindresorhus/electron-dl#directory).

**Comment by markypython** [comment]
Closed via #141
