### ISSUE TITLE
Rethink Custom Styles

### ISSUE THREAD

**Issue by timche** [timche/gmail-desktop#121]
As of now, it's very difficult to keep up with CSS class changes which results in breaking our custom styles constantly. We should come up with a compromise where we apply "safe" custom styles that are breaking rarely.

Opinion @markypython ?

**Comment by markypython** [comment]
@timche I've thought about how to do the custom styles better and I think it would require using fewer class names and more selector hierarchy.  Styles like this `#gb > div > div:last-of-type > span`.
