### ISSUE TITLE
Incorporate Simplify Gmail

### ISSUE THREAD

**Issue by richardmalone** [timche/gmail-desktop#124]
I would like to see the Simplify Gmail chrome extension incorporated into Gmail-Desktop.
![01](https://user-images.githubusercontent.com/6492842/59273485-3cfd0d00-8c50-11e9-9102-0c92be2a3817.png)
This extension reduces the interface to a bare minimum, bringing the simplicity of Google Inbox to Gmail.

I think it would fit really nicely into the Gmail Desktop app and would attract Inboxer users across. 

[https://simpl.fyi/](https://simpl.fyi/)

Thank you for a fantastic application.

**Comment by timche** [comment]
Thanks for this suggestion!

In the past we had issues with Google changing CSS classes and we couldn't keep up with the changes. I'll have a look at that project and get in contact with the author if he is interested in a partnership, so we can consume that project as a dependency.

**Comment by timche** [comment]
As we have fixed our custom styles, there is currently no need to implement simplify Gmail. We have added support for user custom CSS in our latest release.

**Comment by alecmev** [comment]
Unfortunately, the things that Simplify does can't be achieved with just CSS. I recommend [taking a closer look](https://simpl.fyi/), it has a better landing now, the screenshots should give you a good idea even without installing :wink:

**Comment by macx** [comment]
I sugges to re-open this issue, because User-Styles isn't the same as this extension.

**Comment by avelino** [comment]
@timche css customization would not be the responsibility of the `gmail-desktop` project, but rather the responsibility of **Simplify**

Simplify is a paid solution, it would be important to have an option to **activate** or **deactivate**

Simplify is a plugin and you can use this electronjs api to load plugin:
- https://www.electronjs.org/docs/latest/api/extensions
- https://github.com/getstation/electron-chrome-extension
