### ISSUE TITLE
Notification on MacOS didn't show up

### ISSUE THREAD

**Issue by marcinlesek** [timche/gmail-desktop#125]
Hello,

firstly, thanks for developing & maintaining this app. 👏 I'm guessing that notifications are turned on by default (they are mentioned in `README.md` file) - but on my Mac they don't appear at all.

- Gmail Desktop Version: 2.9.2 (2.9.2.373)
- OS Version: Mojave 10.14.5 (18F203)

Steps to Reproduce:

1. Turn on Gmail Desktop
2. Log into account
3. Get any email to main inbox
4. Check that no notification has been received / show up

Please tell me if I couldn't find option to turn them on or something broke up. Thanks in advance!

Best regards,
Marcin

**Comment by timche** [comment]
Thanks for reporting this issue. I'm looking into it 👍

**Comment by timche** [comment]
Notifications seem to be working again, at least for me. Anyone else too?

**Comment by fatihturan** [comment]
> Notifications seem to be working again, at least for me. Anyone else too?

I can see the notification badge and hearing the sound but notification banner doesn't show at the moment.

**Comment by marcinlesek** [comment]
> Notifications seem to be working again, at least for me. Anyone else too?

I see only badge on the app icon unfortunately - any notifications show up 💔 

I also get this error after a while of Gmail Desktop turned on:

<img width="532" alt="Screenshot 2019-06-21 at 11 01 03 PM" src="https://user-images.githubusercontent.com/13199192/59951778-3c4b4e80-947a-11e9-99fa-c69e9633b5cc.png">

Best,
Marcin

**Comment by marcinlesek** [comment]
Hey @timche, any updates? Notifications should be enabled by default, yea?

**Comment by timche** [comment]
> Notifications should be enabled by default, yea?

Yes.

---

Notifications are very inconsistent for me, I need to look into that, sorry for the delay. If there is anyone who can help, I'd really appreciate it.

**Comment by timche** [comment]
Notifications are working fine me (again) for a while. I'm closing this issue for now, but if this should be still an issue, feel free to let me know, thanks.

**Comment by sndrs** [comment]
sorry to say, i'm not getting any notifications :)

running 2.12.1.472 on mac os 10.14.6

nothing in console... anywhere else i should check?

**Comment by markypython** [comment]
@sndrs Do you have notifications turned on in the Gmail settings?

![2019-09-18_06-03-31](https://user-images.githubusercontent.com/25914066/65143308-424dbe80-d9da-11e9-9343-3bcb18d8a4c7.png)

**Comment by sndrs** [comment]
🤣

no...i'm an idiot, thank you!
