### ISSUE TITLE
macOS Text Replacement Doesn't Work in Compose Window

### ISSUE THREAD

**Issue by fatihturan** [timche/gmail-desktop#128]
- Gmail Desktop Version: 2.9.2
- OS Version: macOS Mojave 10.14.5

Steps to Reproduce:

1. Opening compose window
2. With using macOS' text replacement feature I am writing alias and expecting expand into sentence ([like this](https://cl.ly/a32f111ade20)) but it doesn't.

**Comment by markypython** [comment]
Related to https://github.com/electron/electron/issues/15535

**Comment by fatihturan** [comment]
This issue has been fixed with Gmail Desktop 2.15.0 version which includes Electron 7. 👍
