### ISSUE TITLE
Account Switch Button is Hiding When Custom Styles Enabled

### ISSUE THREAD

**Issue by fatihturan** [timche/gmail-desktop#131]
* Gmail Desktop Version: 2.9.2
* OS Version: macOS Mojave 10.14.5

Steps to Reproduce:

If I enable "Custom Styles" from the Settings > Appearance menu then Account Switcher button is hiding.

**Comment by fatihturan** [comment]
Now search bar is gone too:

<img width="1124" alt="image" src="https://user-images.githubusercontent.com/26871/63501034-9779db80-c4d3-11e9-975b-47b0b5d53dd3.png">

**Comment by timche** [comment]
Fixed with #135

**Comment by fatihturan** [comment]
Thank you @timche! 👍🏻
