### ISSUE TITLE
When switching to a delegated accounts, further opens of the application load that account by default

### ISSUE THREAD

**Issue by cipriancraciun** [timche/gmail-desktop#133]
- Gmail Desktop Version: 2.9.2
- OS Version: Linux, openSUSE Tumbleweed (up-to-date)

Steps to Reproduce:

1. open the GMail application, and use an account that has access to delegated GMail accounts;  (this is similar to login-in into multiple accounts, but as opposed to that feature, it doesn't imply an actual login, but will provide only access to GMail for that account;)
2. open the GMail application, and from the account selector, select an delegated account;
3. close the main GMail window (which has the "default" account);
4. close the "delegated" GMail window;
5. from the tray click the GMail application icon;
6. the UI starts, but loads the delegated account by default, instead of the "default" GMail account that was used initially when starting the application;

Initially I thought that the application "remembers" the last GMail URL, or keeps the window hidden.  However no matter in what order I close the windows (delegated one, then default;  or default then delegated), it always opens the delegated account.

**Comment by timche** [comment]
Will be obsolete with #25
