### ISSUE TITLE
mailto: links do not work

### ISSUE THREAD

**Issue by richardmalone** [timche/gmail-desktop#14]
Clicking on someone's email address results in a modal dialogue saying:

_Grr! A popup blocker may be preventing Gmail from opening the page. If you have a popup blocker, try disabling it to open the window._

If you click okay, the page goes blank and the app needs restarting.

Thanks, Rich

**Comment by timche** [comment]
Thanks for reporting this issue.

If anyone has some time to fix it, it can be done like this: https://github.com/timche/gmail-desktop/blob/master/src/app.js#L70-L79

Otherwise I'll try asap, but can't promise an exact date.

**Comment by timche** [comment]
Fixed in [v2.0.0](https://github.com/timche/gmail-desktop/releases/tag/v2.0.0)
