### ISSUE TITLE
Add user setting to disable all custom styling

### ISSUE THREAD

**Issue by cyfrost** [timche/gmail-desktop#151]
As was discussed multiple times before, custom styling can sometimes cause issues due to changes in Gmail's stylesheets. Since these changes are not ephemeral, they'd require an entirely new release to fix the styling issues (in case some poppped up). My suggestion is to have a global user setting to disable all custom styling to let any UI/UX disruptions subside until an update can be released.

Having said that, I'm afraid this is currently a non-issue judging from the picture below; we already have a few options that involve toggling custom styling but am not sure if these represent all custom CSS injected. If yes, then please feel free close this issue.

![image](https://user-images.githubusercontent.com/12471103/64920757-a86af380-d7d8-11e9-9e8a-2e88d6a2d4e7.png)

**Comment by markypython** [comment]
@cyfrost The picture you are showing is the result of a recent change which split the custom styles into multiple pieces and made it completely configurable.  When all the options are turned off, no custom styles will be applied.

I'll close this as a non issue.
