### ISSUE TITLE
Dark mode?

### ISSUE THREAD

**Issue by jubishop** [timche/gmail-desktop#160]
This is really cool.  Better and cleaner than Kiwi, Boxy Suite in many ways.  Any chance of another CSS mod for a dark mode? that'd be sexy.

**Comment by cyfrost** [comment]
Just curious: Gmail has a Dark theme via Settings > Themes. What's missing with it?

**Comment by jubishop** [comment]
Well shit.  Nothing I’m just an idiot 😂.  Awesome thanks for the info

**Comment by timche** [comment]
Added dark mode in https://github.com/timche/gmail-desktop/releases/tag/v2.24.0
