### ISSUE TITLE
[Discussion] Issue fixing priorities

### ISSUE THREAD

**Issue by cyfrost** [timche/gmail-desktop#162]
Hi @timche, and @markypython .

This is to discuss what issues/enhancements we need to work on and how much progress is made. Considering the better understanding you both have about the current state of this project, please lets discuss a list of issues (sorted by priority) to be fixed. Fixings bugs before taking up enhancements looks like a good start to me. Thoughts?

With my fairly basic understanding about the issues in this project, I've put this up:
1. Rebranding (related to #94, [this](https://github.com/timche/gmail-desktop/issues/39), and [this](https://github.com/timche/gmail-desktop/pull/104)) --I'm still up for a rebrand unless you've already reached a logical conlusion on this one.
2. Clean external links from Google tracking (#116) --Might positively impact the way (potential) users' perceive this app. Thanks @timche for even bringing this up in the first place!
3. Better handling of network change between sleep states #157 -- Reproducible on Linux/Windows to my understanding, waking the PC/Laptop from Sleep will cause connection issues.
4. Zooming Content or Chaning font-size (#89) --Many users have larger displays and may want to adjust the window zoom to their liking.
5. Option to configure notification content #78 --Improves privacy but will likely need a better notification delivery system, one alternative suggested by @markypython [here](https://github.com/timche/gmail-desktop/issues/157#issuecomment-532430524).
6. Option to disable notifications #76 --Very useful, indeed. Another option is to have a DND mode with configurable timers (say 10mins, 1hr, and co.)
 
Thanks,
Cyrus

**Comment by timche** [comment]
1. Has very low priority. Unless Google contacts us, I wouldn't bother with rebranding for now.
1. Privacy is a huge topic and I very welcome this feature and happy to have it as selling point.
1. I didn't experience any issues, but let's discuss that further in the issue. If it becomes a blocking issue, it should be handled with higher priority for sure.
1. Definitely good to have.
1. This actually requires more work than just few lines, so definitely more planing and medium priority.
1. Also good feature.

As long as no issue is stating that someone is working on it, it's available. In terms of priority, bugs have higher priority than enhancements, but should also be based on complexity.

I definitely see that there are lots of tasks to do and I really appreciate that the community is contributing to this project!

**Comment by markypython** [comment]
We could bring back the project board so we can sort issues based on priority.  @timche Thoughts?

**Comment by timche** [comment]
Not sure if it will help us as any issue can be taken regardless the priority. So you would like to work, feel free to take it :)

**Comment by markypython** [comment]
@timche Can we close this as it seems that the discussion is done?

**Comment by timche** [comment]
Sure
