### ISSUE TITLE
dock icon unread count incorrect

### ISSUE THREAD

**Issue by sndrs** [timche/gmail-desktop#166]
My dock icon count appears to be stuck. 

there's nothing in the logs or console in developer mode?

![image](https://user-images.githubusercontent.com/867233/67006657-992fdc00-f0dd-11e9-9cbd-a699ca595c23.png)

restarting, reloading, updating the read count in gmail itself doesn't seem to fix it...

- Gmail Desktop Version: 2.13.0.489
- OS Version: 10.15

Steps to Reproduce:

1. open app
2. icon unread count goes to 3
3. gmail says unread is 36

realise it's not a lot to go on! let me know if you need any more info?

**Comment by sndrs** [comment]
ah ha! it's only showing the `3` of `36`. got unread to 20s and saw this:

![image](https://user-images.githubusercontent.com/867233/67006969-3f7be180-f0de-11e9-80bf-e9b3b3b464b5.png)

**Comment by markypython** [comment]
This was fixed in #164 but we haven't released a new version since.  I'll release a new version right now.

**Comment by markypython** [comment]
Fixed in v2.13.1

**Comment by sndrs** [comment]
wow that's service :)

amazing, thank you 👍
