### ISSUE TITLE
Random error when restarting

### ISSUE THREAD

**Issue by shamoons** [timche/gmail-desktop#167]
This is for Windows:
![image](https://user-images.githubusercontent.com/1019677/67108407-6c8ec980-f19c-11e9-9b8f-bec197e584b4.png)

**Comment by cyfrost** [comment]
Thanks for the report. Is this happening on the latest app version?

**Comment by shamoons** [comment]
Yes. I just uninstalled and reinstalled. Same error

**Comment by cyfrost** [comment]
Okay, am working on this.

**Comment by cyfrost** [comment]
@shamoons There's already a fix available with [this](https://github.com/timche/gmail-desktop/pull/165) PR contributed by @zzpxyx, Once its merged and we have a new release you should no longer face this bug. I've verified that it works by cherry-picking his PR to my local branch on a Windows install.

**Comment by shamoons** [comment]
Now that's customer service with a smile! Thanks for looking at it so quickly.

**Comment by markypython** [comment]
Fixed in [v2.13.2](https://github.com/timche/gmail-desktop/releases/tag/v2.13.2)
