### ISSUE TITLE
How can I go back from the print view?

### ISSUE THREAD

**Issue by shamoons** [timche/gmail-desktop#170]
- Gmail Desktop Version:
- OS Version: Windows 10

Steps to Reproduce:

1. Open an email, and click print
![image](https://user-images.githubusercontent.com/1019677/67160038-42fbac80-f31a-11e9-9052-99d1f55606d2.png)

2. As expected, a preview version of the email opens up:
![image](https://user-images.githubusercontent.com/1019677/67160053-7e967680-f31a-11e9-8ec3-2d2640576307.png)

3. But now, I can't get back to my email list. Even if I restart the application, it loads the preview of that specific email. I have to switch to debug mode and restart to clear it.

**Comment by timche** [comment]
> Even if I restart the application, it loads the preview of that specific email.

That means you didn't restart the app correctly. On launch, it always loads `https://mail.google.com`: https://github.com/timche/gmail-desktop/blob/master/src/app.ts#L92

Nevertheless, the printing should open a new window and it's a bug.
