### ISSUE TITLE
Installation via Snap and Flathub

### ISSUE THREAD

**Issue by tracker1** [timche/gmail-desktop#171]
Would be nice to see this in Flathub and/or Snap for easy Linux install/discovery.

**Comment by cig0** [comment]
HI,

I downloaded the Snap package **gmail-desktop-2.20.4-linux.snap** to give it try, got the following error message:

`error: cannot find signatures with metadata for snap "gmail-desktop-2.20.4-linux.snap"`

Could it be isn't published on the Snapcraft store? At least, I couldn't find it there.

**Comment by timche** [comment]
We haven't submitted it to the Snapcraft store.

**Comment by timche** [comment]
I'll try to release it in the Snap Store, but I'll need to get ownership of the [currently registered snap](https://snapcraft.io/gmail-desktop). Will get back to you later.
