### ISSUE TITLE
Hyperlinks don't work from Ubuntu

### ISSUE THREAD

**Issue by shamoons** [timche/gmail-desktop#173]
I have Ubuntu 18.04 and clicking links in my email does not open the browser

**Comment by HearMeWhisper** [comment]
In the latest ubuntu, in my experience, doesn't allow you to set this app as a default email client

**Comment by timche** [comment]
The core team is not unfortunately not using Ubuntu/Linux, so we need some help finding the issue.

**Comment by timche** [comment]
We've just released [v2.16.1](https://github.com/timche/gmail-desktop/releases/tag/v2.16.1). Can you please check if this might have solved this issue @shamoons? Thanks.
