### ISSUE TITLE
GitHub notifications links aren't working

### ISSUE THREAD

**Issue by Ivan-Brigidano** [timche/gmail-desktop#176]
Versions:

- Gmail Desktop Version: Last one (2.15.0)
- OS Version: Last one (macOS Catalina 10.15.2)

Steps to Reproduce:

1. Receive an automatic GitHub notification mail
2. Try to tap "View Issue/Pull Request" link

This should launch a new window with that Issue/PR but isn't launching any safari window. It sometimes marks the mail as read and sometimes not.

**Comment by timche** [comment]
Thanks for reporting this issue. This is fixed in [v2.16.1](https://github.com/timche/gmail-desktop/releases/tag/v2.16.1).
