### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by YijunYuan** [timche/gmail-desktop#184]
As you may know, Gmail is inaccessible in mainland China, we have to use a proxy server (the popular choice is SOCK5 proxy). So it's wonderful if this Gmail desktop client support proxy settings, or, in order to use this, we have to use a global proxy, which is not always convenient.

**Comment by timche** [comment]
Related: https://www.electronjs.org/docs/api/session#sessetproxyconfig

**Comment by YijunYuan** [comment]
> Related: [electronjs.org/docs/api/session#sessetproxyconfig](https://www.electronjs.org/docs/api/session#sessetproxyconfig)

This should be helpful. Also, I solved the problem with proxifier.
