### ISSUE TITLE
"manage account" height bug

### ISSUE THREAD

**Issue by mIcHyAmRaNe** [timche/gmail-desktop#186]
- Gmail Desktop Version: 2.17.0
- OS Version: Windows 10

Steps to Reproduce:

1. login to an account
2. click in the profile icon in the top-right corner

the width of the appeared card seems to be good, but the height is bad 

![gmail](https://user-images.githubusercontent.com/17873513/79056310-3f0b7000-7c55-11ea-8e70-fb016e389097.PNG)

and i have to add that the about gmail desktop didn't work for me while checking to add version info to this issue... nothing happen when clicking on it

**Comment by hell0-Wor1d** [comment]
only occur in "Compact Header" mode.
wrong css rule: https://github.com/timche/gmail-desktop/blob/master/css/style.css#L66

**Comment by timche** [comment]
Thanks for figuring out @hell0-Wor1d 

Would anyone mind fixing this? I'm quite busy lately, sorry.

**Comment by timche** [comment]
Fixed fccd21e3a5bb26f1c7485d9eb78405703c610ddf
