### ISSUE TITLE
show destination URL for links hovered over

### ISSUE THREAD

**Issue by Viqsi** [timche/gmail-desktop#187]
One very useful way to avoid phishing is to be able to see the URL that a link is actually going to, Unfortunately, this isn't presently possible in Gmail Desktop. Most browsers handle this via a status bar, showing therein the destination URL of the link presently being hovered over. It would be nice if this, or some kind of tooltip, or some other display of the current hovered-over link's destination could be implemented.
Thanks!

**Comment by timche** [comment]
We have added a confirmation dialog with showing the URL before the URL will be opened in the browser with #188. Hosts can be trusted for the future. It's similar to what VSCode has implemented.
