### ISSUE TITLE
System tray icon not visible anymore on Linux

### ISSUE THREAD

**Issue by cipriancraciun** [timche/gmail-desktop#191]
- Gmail Desktop version: 2.18.1
- OS version: openSUSE Tumbleweed (rolling)
- window manager: `i3`

The system tray icon is not visible anymore.  The system tray icon was working in 2.17.0.

(I have tried enabling / disabling and then restarting, and even starting with a fresh profile.)

**Comment by timche** [comment]
It might be possible that this was introduced with upgrading from Electron v7 to v8.

**Comment by cipriancraciun** [comment]
I could try different builds if necessary.

**Comment by cipriancraciun** [comment]
Apparently with v0.20.1 the problem was solved.
