### ISSUE TITLE
Notifications Not Working on Windows

### ISSUE THREAD

**Issue by kylejbrk** [timche/gmail-desktop#192]
- Gmail Desktop Version: 2.20
- OS Version: Windows 10

Steps to Reproduce:

None

Hard to describe since I am not sure how notifications work normally. However after a fresh install and reinstall, it seems that I do not get any notifications on Windows. Also the badge counts dont show up in the task tray.

**Comment by pinguluk** [comment]
Same issue

**Comment by pinguluk** [comment]
It seems you have to enable the desktop notifications by going on Gmail settings -> General -> Desktop notifications and set it to New mail notifications on. But still no badge counts.

**Comment by timche** [comment]
> It seems you have to enable the desktop notifications by going on Gmail settings -> General -> Desktop notifications and set it to New mail notifications on. But still no badge counts.

Unread badge count feature only exists on macOS. On Windows/Linux the icon is either monochrome (no unread) or in color (unread).
