### ISSUE TITLE
Compact header doesn't show all the content on G Suite accounts

### ISSUE THREAD

**Issue by Ivan-Brigidano** [timche/gmail-desktop#193]
As you can see in the image that I attach, the company logo is not fully visible.

<img width="1158" alt="Captura de pantalla 2020-05-13 a las 21 53 03" src="https://user-images.githubusercontent.com/47502355/81858688-6612d580-9564-11ea-88ac-99d951977cc8.png">

**Comment by timche** [comment]
Fixed in https://github.com/timche/gmail-desktop/releases/tag/v2.24.0
