### ISSUE TITLE
Support dark mode ?

### ISSUE THREAD

**Issue by duongle26** [timche/gmail-desktop#195]
![image](https://user-images.githubusercontent.com/28813618/83289330-18a69180-a20f-11ea-80da-8c1c7d3ba225.png)

I know there is a default dark mode, but can you adopt this way of style in your app. Greate app, btw

**Comment by mskelton** [comment]
This was discussed in #75 where we decided to not create a custom dark mode in favor of the default Gmail dark theme.  Maintaining custom styles for Gmail is super hard as their class names are meaningless and you often has to rely on the dom structure instead.

**Comment by duongle26** [comment]
@mskelton thanks for your answer. As I don't want to open another issue just for a question, I will put it here: How can I enable push notification, for example, something like this shows up when a new email arrives?
![image](https://user-images.githubusercontent.com/28813618/83293170-94a3d800-a215-11ea-8186-fa09d7d321c9.png)

**Comment by mskelton** [comment]
Have you enabled desktop notifications in gmail?  This article explains how to: https://support.google.com/mail/answer/1075549?co=GENIE.Platform%3DDesktop&hl=en

**Comment by duongle26** [comment]
Got that working, thanks

**Comment by ipkpjersi** [comment]
I attempted to enable dark mode through Gmail settings but it appears I am missing the settings button:

![](https://i.imgur.com/lQDWVxJ.png)

Should I create a new issue for this? I am not sure if this is worth creating an issue for or if this is an issue with Gmail itself and not with this app?

**Comment by cipriancraciun** [comment]
@ipkpjersi Go in the `gmail-desktop` menu (by pressing `Alt` if it is hidden), then `Settings > Appearance > Hide Support` and uncheck that.  Then you can see the usual GMail settings button in the usual place.

**Comment by ipkpjersi** [comment]
That worked, thanks.

**Comment by cipriancraciun** [comment]
> Although I do wish the body of emails had a dark background with white text, that would be cool.

:)  Yes...  I used to have a custom user-style (this is something that `gmail-desktop` supports now) that would override those colors, but reverse engineering GMail's theme CSS classes is like trying to reverse-engineer assembler code...

So it is technically possible, but its something strictly tied to the theme you are choosing, and unfortunately can break at any moment due to changes done by GMail's team.

**Comment by timche** [comment]
Added dark mode in https://github.com/timche/gmail-desktop/releases/tag/v2.24.0
