### ISSUE TITLE
Fails to login to IDPs like Okta

### ISSUE THREAD

**Issue by cdloh** [timche/gmail-desktop#2]
Logging this to track.

The app fails to login to IDPs like OKTA. Okta seems to have JS errors on the login screen.

**Comment by timche** [comment]
Could you tell me how to reproduce it?

**Comment by cdloh** [comment]
Apologies I didn't give you much information.

I've debugged it further and it looks like It's a due to this issue noted here electron/electron#254

jQuery doesn't load correctly as it detects the module variable.

Couple of options to fix this

1. [Disable node integration in the WebPreferences object on the main window.](https://github.com/electron/electron/issues/254#issuecomment-42351776)
2. add a preload script similar to [this](https://github.com/electron/electron/issues/5827#issuecomment-223578761) to load jQuery into the dom on load

Thoughts?

**Comment by timche** [comment]
I think option 1 would be better,  because jQuery would just add another dependency.
