### ISSUE TITLE
Add to CC Recipients Shortcut Toggling Inspector Pane

### ISSUE THREAD

**Issue by fatihturan** [timche/gmail-desktop#203]
- Gmail Desktop Version: 2.20.1
- OS Version: macOS Mojave 10.14.6

Steps to Reproduce:

1. Click on the Compose button to open the New Message window.
2. Press on the CMD+Shift+C from the keyboard.

When reproducing these steps it's toggling inspector pane on the Gmail Desktop window.

**Comment by timche** [comment]
Fixed in v2.20.2
