### ISSUE TITLE
Cannot edit config file on Linux

### ISSUE THREAD

**Issue by ipkpjersi** [timche/gmail-desktop#204]
I am presented with this error when attempting to edit the config file:
![](https://i.imgur.com/fkanp27.png)
- Gmail Desktop Version: 2.20.2
- OS Version: Ubuntu 18.04 with Xfce 4.12

Steps to Reproduce:

1. Install via deb on Ubuntu 18.04 File -> Open 
2. Go to Settings -> Advanced -> Edit Config File

**Comment by timche** [comment]
This has been introduced with the upgrade of Electron: ed373173d706214c89b7386c7501d292283ef390

We need to upgrade `electron-store` that supports the latest Electron version.

**Comment by pilotstew** [comment]
Any workaround for this?
