### ISSUE TITLE
Email notifications not working on Linux

### ISSUE THREAD

**Issue by ipkpjersi** [timche/gmail-desktop#205]
I am not recieving any email notifications, I am only getting the red tray icon when I recieve an email. I am using Linux.

- Gmail Desktop Version: 2.20.2
- OS Version: Ubuntu 18.04 with Xfce 4.12

Steps to Reproduce:

1. Recieve an email
2. There is no email notification

**Comment by cipriancraciun** [comment]
(I am currently using 2.20.1, so unless this is a bug introduced in this latest patch, see my reply bellow.)

I've been using `gmail-desktop` for quite some while on Linux (openSUSE Tumbleweed) with `i3` window manager (thus a similar lightweight / non-Gnome / non-KDE environment), and notifications always worked, thus please check the following:
* are you receiving notifications from other applications (except Chromium / Firefox)?  (I say except these browsers, as they have their own built-in mechanism;)
* make sure that you have enabled `new mail notifications on` from the GMail settings;  (you have to uncheck `Settings > Appearance > Hide Support` to see the normal GMail settings button in the usual place, and from there go to `General`;)
* do you have a `libnotify` compliant "displayer"?  (for example I use `dunst` https://github.com/dunst-project/dunst);
* just run `notify-send test` and see if you see any `test` notification;  (if not please see the previous line;)

**Comment by ipkpjersi** [comment]
I believe I had display notifications turned off in GMail settings, so I think that was the issue. It seems you solved two of the issues I've had so that helps a lot. I wish there was a way to force notifications to only one specific monitor instead of the monitor with my current mouse but I guess that is not possible?

I am guessing there is no way to get a display of the count of unread emails in the tray icon?

**Comment by cipriancraciun** [comment]
> I wish there was a way to force notifications to only one specific monitor instead of the monitor with my current mouse but I guess that is not possible?

That is something you have to configure in your notifications display tool.  (For example in case of `dunst` you can use the `monitor` and `follow` options to configure this.)

> I am guessing there is no way to get a display of the count of unread emails in the tray icon?

My guess is that is technically possible, however I believe it would require us to have one icon per number of unread emails (so say up to 10?).

**Comment by ipkpjersi** [comment]
> That is something you have to configure in your notifications display tool. (For example in case of dunst you can use the monitor and follow options to configure this.)

I think since I'm using xfce4, I'm using xfce4-notifyd, seems like xfce4-notifyd-config does have support for running notifications (possibly even specific for one app) on the primary monitor: https://docs.xfce.org/apps/notifyd/preferences, but perhaps not with my version of xfce4-notifyd-config: http://i.imgur.com/zcJjll1.png unless I'm using a different notification daemon altogether? No idea, I'm still fairly new to Linux, only been running it for 3 years on my desktop and this seems somewhat nontrivial...

> My guess is that is technically possible, however I believe it would require us to have one icon per number of unread emails (so say up to 10?).

I think that definitely would be cool to have, one icon each for 1 to 9, then 10 or more could be displayed as 9+.
