### ISSUE TITLE
Use forward/back controls to navigate to/from the inbox and other pages

### ISSUE THREAD

**Issue by owenshaupt** [timche/gmail-desktop#208]
When using the Gmail web app, I often use the back shortcut button on my mouse to go back to the inbox and, less often, use the forward shortcut button on my mouse to return to an email I backed out of. This might apply to other methods, _e.g._ using backspace to go back.

**Comment by timche** [comment]
Thanks for your suggestion. So we could just use the back and forward buttons to literally go back and forward like in the browser.

**Comment by owenshaupt** [comment]
Yes! Given my short experience with the app, it seems like it could fit in as something hideable/togglable like the footer and sidebar.

**Comment by pedrodonkey** [comment]
+1 for this. It's become second nature on a mac using the swipe gestures on the magic mouse to go back to inbox which i assume is just invoking the browsers back command. Would def be a nice to have.

**Comment by CrazyHoodlem** [comment]
I too would like to see this added, mainly because I wanted to add another account but then decided not to. I had to restart because there was no way of going back to my email.
