### ISSUE TITLE
Arch + Vivaldi: Login and user-agent problem.

### ISSUE THREAD

**Issue by Davetheraveuk** [timche/gmail-desktop#216]
- Gmail Desktop Version: 2.20.2-1
- OS Version: Arch Linux 64-bit.

Steps to Reproduce:

1. Install from the AUR
2. Run program and attempt to log in.

I have tried changing the user-agent via github page here:
https://github.com/timche/gmail-desktop#i-cant-sign-in-this-browser-or-app-may-not-be-secure

I use Vivaldi as my web browser.
If you need any more info then get in touch. :)
Thanks, Dave.

**Comment by timche** [comment]
What specific problem are you facing? Please specify the error.

**Comment by HagaiHargil** [comment]
I'm on Arch, installed from AUR v2.20.4 with Firefox and I'm having the same issue. 

It gives the "using non-supported user agent" message on login and the screen tells me that the app is insecure. I tried manually changing my user agent to basically all of the options in the link, and a few more, but to no avail - the issue persists.

**Comment by timche** [comment]
Please let me know if this issue still persists and we can re-open this again.

**Comment by pilotstew** [comment]
gmail-desktop 2.25.3-2 via AUR

I am having this same issue. Exactly as above, I've tried all the Firefox and Chrome user agents manually entered into the config file as well as the automatic fix.
