### ISSUE TITLE
"Hide Right Sidebar" only hides icons, not container

### ISSUE THREAD

**Issue by eriktdesign** [timche/gmail-desktop#217]
- Gmail Desktop Version: 2.20.4.0
- OS Version: Windows 10.0.18363

Steps to Reproduce:

1. Go to Settings->Appearance->Hide Right Sidebar
2. Icons are hidden, but the container they were in remains as empty space.

**Comment by timche** [comment]
The "Hide Right Sidebar" setting has been removed in favour of the native Gmail feature on the bottom right.
