### ISSUE TITLE
On Linux the sys-tray icon opens a menu on left-click

### ISSUE THREAD

**Issue by cipriancraciun** [timche/gmail-desktop#219]
- Gmail Desktop Version: 2.20.4
- OS Version: Linux, OpenSUSE Tumbleweed

Steps to Reproduce:

In the previous version (2.20.2), when left-clicking the sys-tray icon opened-up the GMail window;  currently it shows a menu with `Show` and `Quit` just like when pressing right-click.

Possibly this issue is related to #196, however that issue is from July, thus my assumption predating 2.20.2, and OSX, it might be a different cause.

Moreover I've observed exactly the same behaviour with the updated Slack client, thus my assumption is that this is most likely an Electron bug.  Searching their issues I've stumbled upon the following:
* https://github.com/electron/electron/issues/21576
* https://github.com/electron/electron/issues/14941

**Comment by timche** [comment]
I think in Electron they might have changed this behaviour, so I wouldn't necessarily consider this as a bug. I'll check if this can be configurable.

**Comment by cipriancraciun** [comment]
Although I agree this is not a "bug" in the software-engineering sense of the word, it is an unexpected change of past behaviour.  Therefore from a "functionality" point of view, or UX point of view, it is at least a minor "bug".  :)

(Just imagine one updates his OS, and all of a sudden right-click and left-click are swapped.  It wouldn't be a bug, but it would be frustrating as hell.)  :)

**Comment by timche** [comment]
Closing since it's a bug that Electron needs to fix.
