### ISSUE TITLE
Unidentified developer

### ISSUE THREAD

**Issue by markypython** [timche/gmail-desktop#22]
When downloading the latest dmg file, Mac complains that it is from an unidentified developer.  While you can bypass this by right clicking and selecting open from the context menu, it would be best to not have this experience.

<img width="409" alt="unidentified developer" src="https://user-images.githubusercontent.com/25914066/52902018-7ce74280-31d0-11e9-9f20-6c911248940e.png">

**Comment by timche** [comment]
You're right. This is due to not having an Apple developer certificate and the app being [unsigned](https://www.electron.build/code-signing). I'd need to pay for an Apple developer certificate which I haven't done yet.

**Comment by markypython** [comment]
I just released version 2.1.0 with the most recent changes.  However, it seems that on Mac it doesn't auto update because according to auto updater:

> macOS application must be signed in order for auto updating to work.

https://www.electron.build/auto-update

**Comment by timche** [comment]
I will look into code signing asap. If I understand correctly, it actually doesn't require me to be part of the Apple Developer Program, which costs 99 USD, but I need to create certificates locally to sign apps.

**Comment by timche** [comment]
App is now signed since [v2.2.0](https://github.com/timche/gmail-desktop/releases/tag/v2.2.0).
