### ISSUE TITLE
Add Apple Silicon support

### ISSUE THREAD

**Issue by restfuladi** [timche/gmail-desktop#224]
Electron 11 supports arm64, would it be possible to get native build? Love the app, thanks!

**Comment by timche** [comment]
Electron will be upgraded to v11 in #223. Please stay tuned.

**Comment by timche** [comment]
@restfuladi can you please test if the arm64 version works in this test build? https://github.com/timche/gmail-desktop/suites/2194117774/artifacts/45264896

**Comment by restfuladi** [comment]
> @restfuladi can you please test if the arm64 version works in this test build? https://github.com/timche/gmail-desktop/suites/2194117774/artifacts/45264896

I just installed the .dmg from the download and Activity Monitor says "Architecture Intel"

**Comment by timche** [comment]
Thanks. I'm [currently building an universal app](https://github.com/timche/gmail-desktop/runs/2046961991?check_suite_focus=true) for you to try again.

**Comment by timche** [comment]
New test build: https://github.com/timche/gmail-desktop/suites/2194300285/artifacts/45269589

**Comment by restfuladi** [comment]
Stuck here, yubikey is inserted.

<img width="477" alt="image" src="https://user-images.githubusercontent.com/14058796/110217824-30056000-7eae-11eb-8c97-2879df9ad431.png">

**Comment by timche** [comment]
Can you elaborate please? Is it frozen? Did you try multiple times?

**Comment by restfuladi** [comment]
Yes tried it multiple times. It's not frozen, the animated blue line keeps cycling and the page is waiting for the security key without failing over to the "try a different way" screen.

**Comment by timche** [comment]
Can you please try the test build and latest release again, just to verify that it's not an issue with Gmail or the security key itself.

**Comment by restfuladi** [comment]
It was my mistake, it was expecting me to touch the key. The UI doesn't change at all when you insert it so I assumed it wasn't detected. Once I touched it it logged in and seems to be working normally.

**Comment by timche** [comment]
Can you confirm that the process architecture is arm64?

**Comment by restfuladi** [comment]
<img width="725" alt="image" src="https://user-images.githubusercontent.com/14058796/110219771-0e5da600-7eb9-11eb-9e17-02cc2c8e6357.png">

**Comment by timche** [comment]
Awesome, thanks. I'll release this.

**Comment by timche** [comment]
Released in [v2.21.1](https://github.com/timche/gmail-desktop/releases/tag/v2.21.1).

**Comment by timche** [comment]
Can you give me a final confirmation that this release is also working please?

**Comment by restfuladi** [comment]
I haven't seen any issues yet unique to this build. Sent a few emails and archived a few more, so far so good.

**Comment by timche** [comment]
Great, thank you for testing so quickly and being so responsive!
