### ISSUE TITLE
Shows no dock icon in Ubuntu 20.10

### ISSUE THREAD

**Issue by AjdinHusic** [timche/gmail-desktop#225]
- Gmail Desktop Version: v2.20.4
- OS Version: Ubuntu 20.10

Steps to Reproduce:

1. installed the .deb application
2. open the application 

shows following icon in dock:
![image](https://user-images.githubusercontent.com/44066226/109629166-d9adbf80-7b43-11eb-8f25-6b4916cc7773.png)

**Comment by wennaspeedy** [comment]
Also in my case. Manjaro and appimage.

**Comment by timche** [comment]
Can you please test if the dock icon is still missing in this test build? https://github.com/timche/gmail-desktop/suites/2194117774/artifacts/45264895

**Comment by AjdinHusic** [comment]
> Can you please test if the dock icon is still missing in this test build? https://github.com/timche/gmail-desktop/suites/2194117774/artifacts/45264895

Still doesn't work sir.

**Comment by timche** [comment]
Can you please test this build? https://github.com/timche/gmail-desktop/suites/2217074279/artifacts/45890033

**Comment by wennaspeedy** [comment]
> Can you please test this build? https://github.com/timche/gmail-desktop/suites/2217074279/artifacts/45890033

Nope
![image](https://user-images.githubusercontent.com/10447994/110589456-b94eb800-8176-11eb-8320-bf2b18547679.png)

**Comment by wennaspeedy** [comment]
Change your package.json:

**Comment by wennaspeedy** [comment]
I fixed it, check my pull request.

**Comment by timche** [comment]
Fixed with #228

**Comment by timche** [comment]
Released in [v2.21.2](https://github.com/timche/gmail-desktop/releases/tag/2.21.2)

**Comment by AjdinHusic** [comment]
@timche Still no app icon in v.21.2.

**Comment by timche** [comment]
Works for me on latest version 2.22.0:
![Screen Shot 2021-03-11 at 14 01 02](https://user-images.githubusercontent.com/8075074/110798610-41fe4e80-8272-11eb-879c-b8d11f3b2056.png)

**Comment by AjdinHusic** [comment]
Do I need to logout / lock  again maybe? I already uninstalled previous version and installed this one,
The version also seems to be missing log files in /opt folder, nut sure if that is intended or means anything to you, but maybe it is expected I don't know.

**Comment by timche** [comment]
I figured out that the icon is still not working with the `.deb` package. We've fixed it only for the `.AppImage` file recently, so it was another bug.

I've released a fix for the `.deb` package in [v2.23.0](https://github.com/timche/gmail-desktop/releases/tag/2.23.0)

CC @AjdinHusic

**Comment by timche** [comment]
@AjdinHusic please let me know if it works for you now. I've tested the `.deb` package on Ubuntu and it works.
