### ISSUE TITLE
Better Dark theme

### ISSUE THREAD

**Issue by AlexR00T** [timche/gmail-desktop#226]
Im really really sorry but cant seem to find an issue or previous feature requests. And sorry but wasn't sure if it should go as a feature request or issue

I have on a my gmail their dark theme but when i use your app and try to compose an email. That compose window is light themed. Would be nice if it could be fixed so that compose window get also that dark theme. Loads of thanks

**Comment by timche** [comment]
A dark theme feature is currently work in progress at #223. Please stay tuned.

**Comment by timche** [comment]
Implemented in 719b01d20fc3f69a71619ecc633efd4155b2e75e and released in https://github.com/timche/gmail-desktop/releases/tag/v2.24.0
