### ISSUE TITLE
Keyboard shortcuts add indentation

### ISSUE THREAD

**Issue by eriktdesign** [timche/gmail-desktop#227]
- Gmail Desktop Version: 2.20.4
- OS Version: MacOS Big Sur 11.1

Steps to Reproduce:

1. Compose a message
2. Use a keyboard shortcut with Cmd (eg Cmd+V, Cmd+B, etc)
3. Current line of compose is indented

For some reason whenever I paste text, or try to make formatting changes using keyboard shortcuts, the current line of text is indented. The line becomes indented one more level each time I press a Cmd+whatever key combination.

**Comment by timche** [comment]
I've experienced this before as well, but it's not happening at the moment.

Can you please check if it's still happening in this test build? https://github.com/timche/gmail-desktop/suites/2194117774/artifacts/45264896

**Comment by eriktdesign** [comment]
@timche I just tested on that build -- still getting the indents.

**Comment by timche** [comment]
We've released few more version since I asked. Can you please install and test the latest version and report back. If you've time, can you also test the latest v3.0.0-alpha pre-release?

**Comment by eriktdesign** [comment]
@timche Doesn't appear to be happening in v3.0.0-alpha.10 -- I'll keep you posted

**Comment by timche** [comment]
Thanks for letting me know. We can re-open this issue when it's happening again.

**Comment by eriktdesign** [comment]
Welp. I just updated to Version 3.0.0-alpha.13 (3.0.0-alpha.13) and it's happening again.

**Comment by timche** [comment]
Can you please check if this actually caused by an update and see if previous versions work fine? 

Also please check if this not system/app related. Possible things to check:
- Reboot
- Different keyboards
- Gmail in browser

**Comment by timche** [comment]
I finally found the root cause of this issue: The custom user agent is loading a slightly different version of Gmail and causes the drag and drop to behave weirdly in Electron.

So if you have this issue, please try disabling `Use User Agent Fix` or removing any custom user agent and use the default user agent instead.

Please let me know if it works for you.
