### ISSUE TITLE
Can't check for updates

### ISSUE THREAD

**Issue by wennaspeedy** [timche/gmail-desktop#234]
- Gmail Desktop Version: 2.24
- OS Version: manjaro - pacman

Steps to Reproduce:

checking update:

LOG: 
```
[2021-03-12 08:13:40.551] [info]  Checking for update
[2021-03-12 08:13:40.552] [error] Error: Error: ENOENT: no such file or directory, open '/opt/Gmail Desktop/resources/app-update.yml'
[2021-03-12 08:13:40.553] [error] Check for updates failed Error: ENOENT: no such file or directory, open '/opt/Gmail Desktop/resources/app-update.yml'

```

**Comment by timche** [comment]
Might it be possible it's because the folder name has a space? Possibly related issue: #94

**Comment by wennaspeedy** [comment]
> Might it be possible it's because the folder name has a space? Possibly related issue: #94

Maybe, but I wont change it manually - this path is hardcoded - name of app - possibly as in issue #94 . You can't choose folder while you're installing linux package. I think space in the name is a mistake (I mean in linux).

**Comment by timche** [comment]
> By intention auto-update is supported only for some formats (on Linux — AppImage). To update pacman/deb/snap/etc please use platform native solutions (package manager).

https://github.com/electron-userland/electron-builder/issues/3844

**Comment by timche** [comment]
You should probably install it from the [Snap Store](https://snapcraft.io/gmail-desktop), but it hasn't been updated there for awhile. I'll try to get ownership of it to update it.

**Comment by timche** [comment]
Related issue: https://github.com/timche/gmail-desktop/issues/171
