### ISSUE TITLE
Show/hide app with tray icon click only

### ISSUE THREAD

**Issue by wennaspeedy** [timche/gmail-desktop#235]
It would be great show/hide app with tray icon on left click only. 

Right click would be same as now it is.

**Comment by timche** [comment]
It's implemented that way already (https://github.com/timche/gmail-desktop/blob/v2.24.0/src/app.ts#L416-L420), but it's really not working consistently on Linux. See https://github.com/electron/electron/issues/14941 and https://github.com/sindresorhus/caprine/issues/1210.
