### ISSUE TITLE
JavaScript error occured in the main process (gmail-desktop-2.24.1-win.zip)

### ISSUE THREAD

**Issue by mafsi** [timche/gmail-desktop#238]
- Gmail Desktop Version: 2.24.1
- OS Version: Windows 10

Steps to Reproduce:

1. Download zip from release
2. unpack & overwrite the existing one
3. start `Gmail Desktop.exe`

![gmail](https://user-images.githubusercontent.com/61430691/111116133-3ced1800-856e-11eb-9be9-a7a8b61daba3.jpg)

**Comment by timche** [comment]
Thanks a lot for reporting this! I've quickly released a fix with https://github.com/timche/gmail-desktop/releases/tag/v2.24.2
