### ISSUE TITLE
Homebrew download fails

### ISSUE THREAD

**Issue by pedrodonkey** [timche/gmail-desktop#239]
Trying go re-install through homebrew and get the following error: 

```
curl: (22) The requested URL returned error: 404 
Error: Download failed on Cask 'timche-gmail-desktop' with message: Download failed: https://github.com/timche/gmail-desktop/releases/download/2.22.0/gmail-desktop-2.22.0-mac.dmg
```

Also, Is there anyway to install the alpha release through homebrew as am eager to test new multi-account updates?

Seems alpha release is not signed and cannot be launched on Mac OS when installed manually through a .dmg download either.

**Comment by timche** [comment]
Unfortunately our cask is currently broken. A PR is open (https://github.com/Homebrew/homebrew-cask/pull/101049) and just waiting to be reviewed and merged.

> Also, Is there anyway to install the alpha release through homebrew as am eager to test new multi-account updates?
Homebrew only allows stable releases, sorry.

**Comment by pedrodonkey** [comment]
Copy that. Will wait for homebrew to approve and merge.

Regarding `Seems alpha release is not signed and cannot be launched on Mac OS when installed manually through a .dmg download either.`

Any chance to get the alpha release signed so i can test on Mac OS through a direct download->install?

**Comment by timche** [comment]
It seems like the certificate on CI is expired. I've refreshed it and currently rebuilding it.

**Comment by timche** [comment]
> Seems alpha release is not signed and cannot be launched on Mac OS when installed manually through a .dmg download either.

@pedrodonkey I've rebuilt the v3.0.0-alpha.1 release with updated macOS certificates. Can you please check again and provide screenshots of the warning/error message if necessary?

Edit: Updating the certificates didn't help, but I've researched a bit and found out that the app must be notarized starting with macOS 10.14.5. The latest https://github.com/timche/gmail-desktop/releases/tag/v2.24.3 is now notarized and the alpha release will follow soon.

**Comment by pedrodonkey** [comment]
Confirmed 2.24.3 installs and launches as expected. Will try v3.0.0-alpha.1 once that get's notarized too.

**Comment by timche** [comment]
Cask has been fixed. 

The newest version v2.25.0 allows changing the release channel. So you can choose the Dev channel and update to v3.0.0-alpha automatically or downgrade with the Stable channel.
