### ISSUE TITLE
Multi-account support

### ISSUE THREAD

**Issue by mskelton** [timche/gmail-desktop#25]
Currently, multi-account support is limited to signing into another Google account using the account selector in the top right, but we should explore better multi-account support.

**Comment by bsramin** [comment]
use this? https://github.com/brrd/electron-tabs

**Comment by timche** [comment]
> use this? https://github.com/brrd/electron-tabs

Looks good 👍

**Comment by gurumark** [comment]
Could you provide clear instructions on how to use electron-tabs?
Thanks.

**Comment by markypython** [comment]
@gurumark I think that is kind of up to whoever ends up doing the PR for this.

**Comment by markypython** [comment]
Not sure how electron tabs will work since we have our own custom header bar.  We may need to consider alternate methods of handling multiple accounts.

**Comment by floriangbh** [comment]
I'm also waiting for multi-account support (but not skilled in TS/JS hehe) !

Thanks for your work !

**Comment by timche** [comment]
I'm planning to work on this using React and https://electronjs.org/docs/api/browser-view.

**Comment by brahimmouhamou** [comment]
What is the status of this feature? 
I'm also willing to test (macOS Catalina 10.15.6)

**Comment by duong-le** [comment]
This is the only missing feature that prevents me from using this app as a daily mail client. Can't wait for it.

**Comment by timche** [comment]
There is something in the works. Stay tuned!
