### ISSUE TITLE
Gmail Desktop 3.0 beta is blocking some keypresses in other apps

### ISSUE THREAD

**Issue by cowboy** [timche/gmail-desktop#263]
**Describe the bug**
I'm running the latest 3.0 beta in Windows 10 and while Gmail Desktop is running (even in the background), I can't use Ctrl-1 or Ctrl-2 or Ctrl-3 in other apps. If I quit Gmail Desktop, I can use those keys again. This issue isn't present in 2.25.3.0, so I've downgraded for now.

**Steps to reproduce the behavior**
1. Run latest 3.0 beta of Gmail Desktop
2. Switch to another program that uses Ctrl + number keys
3. Press Ctrl-1 or Ctrl-2 or Ctrl-3 (I haven't tried other numbers)
4. See nothing happen
5. Quit Gmail Desktop
6. Switch back to the other program
7. Press Ctrl-1 or Ctrl-2 or Ctrl-3
8. See it work

**Expected behavior**
Gmail Desktop should not block any keys in other apps when it's running in the background

**OS**
Windows 10

**Comment by timche** [comment]
Gmail Desktop v3 is in alpha, not beta. This bug has been fixed 3 days ago in [v3.0.0-alpha.6](https://github.com/timche/gmail-desktop/releases/tag/v3.0.0-alpha.6). 

> use local shortcuts to select account instead of registering global shortcuts eb615c5

The latest version is [v3.0.0-alpha.11](https://github.com/timche/gmail-desktop/releases/tag/v3.0.0-alpha.11) or [v3.0.0-alpha.12](https://github.com/timche/gmail-desktop/releases/tag/v3.0.0-alpha.12) (just released and currently building).

**Comment by cowboy** [comment]
Thanks for the quick answer! You may want to add a note about the 3.0 alpha to the issue bug reporting template about checking for the latest build first before posting an issue, I didn't realize that I wasn't on the latest build.

**Comment by timche** [comment]
Thanks for the suggestion. I'll add it to the template.
