### ISSUE TITLE
Window Dragging Suddenly Stops

### ISSUE THREAD

**Issue by fatihturan** [timche/gmail-desktop#270]
**OS**
macOS Big Sur Version 11.2.3 (20D91)

**Gmail Desktop Version**
Version: 3.0.0-alpha.25 (dev)

**Describe the bug**
When I started to dragging window its suddenly stops window dragging operation.

**Media**

https://user-images.githubusercontent.com/26871/114265459-8871d500-99f9-11eb-9ed3-1fd353519ae5.mp4

**Additional context**
I think its depends on mouse drag speed. If I drag the window slowly its works. But if I drag the window with middle or fast mouse speed its suddenly stops the dragging operation.

**Comment by timche** [comment]
Will look into it, thanks.

Related issues: #20926, #21621

**Comment by DinCahill** [comment]
I've been testing dependency updates, and this is fixed in a newer version of electron.

**Comment by timche** [comment]
Thanks @DinCahill for testing. I'll upgrade Electron asap.

**Comment by timche** [comment]
Fixed in 39b3814ff38aad33a34048380254e6a6098949f6
