### ISSUE TITLE
Glitchy icon in Finder?

### ISSUE THREAD

**Issue by seannymurrs** [timche/gmail-desktop#275]
When I view my application list in Finder (in list view), the icon for the app looks somehow glitchy or corrupted. It looks fine if I switch to icon view or if I view it through the Launchpad, but the small icon in list view looks messed up for some reason. I'm attaching a screenshot that shows what I'm referring to.
![CleanShot 2021-04-21 at 10 06 55](https://user-images.githubusercontent.com/6283769/115568009-dd2f0e80-a289-11eb-9870-15e8822045ed.png)

**Comment by timche** [comment]
The same also happens at another OSS app: ![Screen Shot 2021-04-22 at 15 17 34](https://user-images.githubusercontent.com/8075074/115730054-de416800-a37d-11eb-86c4-5a571275cd7f.png)

I suspect that it's a bug with [electron-rebuild](electron-rebuild). I'll have a look at it when I find time.
