### ISSUE TITLE
Click on account tab not responding

### ISSUE THREAD

**Issue by brahimmouhamou** [timche/gmail-desktop#276]
**OS**
macOS Catalina Version 10.15.6

**Gmail Desktop Version**
Version: 3.0.0-alpha.27 (dev)

**Describe the bug**
I have 7 accounts added to the app, but sometimes the 4th account does not react on a tab click.
The problem seems the only occur  around the text, 

I could not find the time to remove all accounts, add them again and verify that the problem still exists,
I will try it as soon as possible.

**Media**
<details open="" class="details-reset border rounded-2">
  <summary class="px-3 py-2 border-bottom">
    <svg class="octicon octicon-device-camera-video" height="16" viewBox="0 0 16 16" version="1.1" width="16" aria-hidden="true"><path fill-rule="evenodd" d="M16 3.75a.75.75 0 00-1.136-.643L11 5.425V4.75A1.75 1.75 0 009.25 3h-7.5A1.75 1.75 0 000 4.75v6.5C0 12.216.784 13 1.75 13h7.5A1.75 1.75 0 0011 11.25v-.675l3.864 2.318A.75.75 0 0016 12.25v-8.5zm-5 5.075l3.5 2.1v-5.85l-3.5 2.1v1.65zM9.5 6.75v-2a.25.25 0 00-.25-.25h-7.5a.25.25 0 00-.25.25v6.5c0 .138.112.25.25.25h7.5a.25.25 0 00.25-.25v-4.5z"></path></svg>
    <span aria-label="Video description account-clicks.mp4" class="m-1">Account clicks</span>
    <span class="dropdown-caret"></span>
  </summary>

  <video src="https://user-images.githubusercontent.com/16655487/115619437-261bad00-a2f4-11eb-9446-2a48b5560795.mp4" data-canonical-src="https://user-images.githubusercontent.com/16655487/115619437-261bad00-a2f4-11eb-9446-2a48b5560795.mp4" controls="controls" muted="muted" class="d-block rounded-bottom-2 width-fit" style="max-height:640px;">
  </video>
</details>

<img width="1585" alt="Gmail_Desktop" src="https://user-images.githubusercontent.com/16655487/115619163-d89f4000-a2f3-11eb-8c15-b205c06fb62b.png">

**Comment by timche** [comment]
This may be fixed alongside #270. If not, please feel free to re-open this issue.
