### ISSUE TITLE
DPreview Links not clickable in emails

### ISSUE THREAD

**Issue by Webreaper** [timche/gmail-desktop#282]
OS Version: MacOS v11.5 beta, M1/ARM64
Gmail Desktop Version: 3.0.0-alpha-27

**Bug Report**
I get notification emails from DPReview.com, but the links aren't clickable. Links are of the form:

   `https://link.dpreview.com/gp/r.html?C=1SN01CG7X5I7V&K=14OYSFCPGWOK0 (truncated)`

(I've had to truncate the link because I think it has implicit auth in the URL; I can forward a sample email, potentially).

**Repro steps:**
1. Subscribe to a topic on the DPReview forums, e.g., this is the one I was looking at: https://www.dpreview.com/forums/thread/4577888?page=2#forum-post-65178397
2. Subscribe to email notifications
3. Wait until somebody posts. 
4. Click link in notification email. Nothing happens. If you right-click, choose 'Copy Link' and paste into the browser it works.

**Expected behavior**
I'm expecting the link to open. Links in other emails open just fine. :)

**Comment by timche** [comment]
If you could forward a sample email to me (email address on my profile), I can look into it.

**Comment by timche** [comment]
Thanks for forwarding. I can click on all links and get a confirmation prompt. Can you please restart Gmail Desktop and try again?

**Comment by Webreaper** [comment]
Even after restarting I still can't click on them (well, I click, but
nothing happens).

Can't see any related errors in the console. Wonder what it could be....?

Don't spend any time on it, it was only in case it was something like a JS
handler blowing up because the link is too long. It's not critical!
