### ISSUE TITLE
Latest Gmail update causing misaligned icons in top right corner

### ISSUE THREAD

**Issue by pedrodonkey** [timche/gmail-desktop#284]
**OS**
macOS

**Gmail Desktop Version**
Version: 3.0.0-alpha.27 (dev)

**Describe the bug**
Looks like the latest Gmail Update is causing some elements below the tabs to be mis-aligned.

- Close re-open the app, hard reload to get latest updates from gmail automatically. 
- Check the new Active drop down in the top right of the screen, Support, Settings and Account Selector are not aligned and spacing above them also seems to be incorrect. Search input location also seems a bit awkward now.

**Media**
![Screenshot 2021-06-10 at 11 09 31 AM](https://user-images.githubusercontent.com/1678763/121489653-f9734000-c9dc-11eb-9ade-95ed3e2a9b08.png)

**Comment by JohnLGalt** [comment]
Seeing the same thing.

**Comment by timche** [comment]
Thanks for reporting this issue. I'll have a look asap.

**Comment by timche** [comment]
There have been few fixes to the top right section since v3.0.0-alpha.28. Let me know if you still have this bug and I'll re-open this issue.
