### ISSUE TITLE
After click on Pop up notification, can't see gmail desktop properly

### ISSUE THREAD

**Issue by VictorS8** [timche/gmail-desktop#291]
**OS**
Windows

**Gmail Desktop Version**
3.0.0-alpha.27 (dev)

**Describe the bug**
When a click trough windows notification pop up, shows nothing on gmail desktop app

**Steps to reproduce the behavior**

1. While gmail desktop is minimized
2. When show a pop up notification
3. Click on pop up
4. Doesn't open the gmail desktop
5. When opening, the screen is black

**Expected behavior**
Just show the gmail desktop after execute step 3 (Click on pop up)

**Media**
Screenshot of how gmail desktop screen become
![gmailDesktop](https://user-images.githubusercontent.com/49603592/130508444-78d43283-f1da-4e24-93b0-ef4d1b01df23.png)

**Additional context**
This not happens every time but have been occurring to me very many times today

**Comment by VictorS8** [comment]
When I double click on Topbar to maximize without clicking on the windows icon, the app works normal and shows the wanted information which showed on pop up notification

**Comment by JohnLGalt** [comment]
Confirmed, I've run into this myself a few times.  Top bar clicking and / or dragging the app to a different window seem to pull it out of its blank phase.

**Comment by VictorS8** [comment]
This only happens with me when I minimeze gmail desktop, when I just change windows with "alt+tab" and click on pop up notification, this bug do not happen

**Comment by JohnLGalt** [comment]
Agreed, minimization is the key here.

**Comment by timche** [comment]
For the record: This bug occurs when the app is maximized and minimized (tested on Windows).
