### ISSUE TITLE
Mouse Back button should go back to search results instead of inbox

### ISSUE THREAD

**Issue by jairoZX** [timche/gmail-desktop#293]
**OS**
Linux

**Gmail Desktop Version**
3.0.0-27  and 2.25.3

**Describe the bug**
After using the search box in gmail, and using the mouse back button it should go back to the search results and not the inbox, basically same behaviour as the back arrow on gmail

**Steps to reproduce the behaviour**

1. search for an email on the inbox
2. click on an email
3. press back button on the mouse
4. goes back to 

**Expected behaviour**
Go back to search results ( gmail does that on the browser)

**Comment by mgray88** [comment]
I'm on macOS and my mouse back button doesn't seem to work at all

**Comment by timche** [comment]
@jairoZX @mgray88 is this still an issue with the latest version [v3.0.0-alpha.31](https://github.com/timche/gmail-desktop/releases/tag/v3.0.0-alpha.31)? Unfortunately I can't reproduce it on macOS and works as described in the expected behaviour.

**Comment by mgray88** [comment]
@timche Unfortunately yea. I have the Logitech MX Master 2S

**Comment by jairoZX** [comment]
@timche same here, tried and same thing happen it goes back to inbox not the search results.

I am on Linux (Ubuntu 21.10)

**Comment by mgray88** [comment]
Interesting, mine doesn't even do that. Just doesn't do anything :(

**Comment by timche** [comment]
@mgray88 are the side buttons working in a browser?

@jairoZX it sounds like the navigation behaves differently on Linux.

**Comment by mgray88** [comment]
@timche Yep, they work pretty much everywhere else I would expect them to work. If it helps, Logitech has a software helper for their hardware, Logitech Options

![](https://user-images.githubusercontent.com/411747/153970858-014cd626-cf33-4e76-bca8-e87854c99349.png)

**Comment by timche** [comment]
@jairoZX @mgray88 can you please test the build available [here](https://github.com/timche/gmail-desktop/actions/runs/1847174808), whether back/forward buttons work and if they work as expected (only going back/forward once in history). If not, can you please open the console in the developer tools and try clicking back/forward buttons and copy-paste the `mousedown` and `mouseup` logs here?

**Comment by jairoZX** [comment]
@timche back and forward buttons works for me now on search, thank you :+1:

**Comment by mgray88** [comment]
@timche Interesting, those two buttons aren't sending any mouseup/down events

**Comment by mgray88** [comment]
Additionally I can't swipe left with my trackpad, and ⌘ ← (command-left) doesn't work either

**Comment by timche** [comment]
@mgray88 thanks for the feedback. There's no support for swiping, but shortcut could be added.

**Comment by mgray88** [comment]
Command-(left/right) works in other browsers (I've only tested Chromium browsers but I would guess it's pretty standard)

**Comment by timche** [comment]
@mgray88 related issue: https://github.com/microsoft/vscode/issues/88029

**Comment by timche** [comment]
@mgray88 you could consider using SensibleSideButtons: https://sensible-side-buttons.archagon.net/

**Comment by timche** [comment]
@jairoZX can you please test [this build](https://github.com/timche/gmail-desktop/actions/runs/1851748458) too?

**Comment by jairoZX** [comment]
tested, also works for back/forward @timche

**Comment by MattKetmo** [comment]
Hello, I've just downloaded version `3.0.0-alpha.37` on macOS and I notice neither  ⌘ ← nor mouse back button work.

Is anyone having the same issue? 
Just trying to understand if it's a regression or something wrong with my setup.

**Comment by JohnLGalt** [comment]
> 

I'm on Windows, not MacOS, but also on Alpha build 37, and after searching, and entering any email in the list, back button on my mouse takes me right back to the list of emails.

And once I've opened an email, after going back to the list, pressing forward takes me back to the email I was just looking at as well.

**Comment by MattKetmo** [comment]
Indeed the [`app-command` event used here](https://github.com/timche/gmail-desktop/blob/b7f44b50b84e0e80013b6821f63af614e58fbd29/src/app.ts#L127-L136) for back & forward navigation is only compatible with Windows & Linux.

![CleanShot 2023-08-22 at 23 31 01](https://github.com/timche/gmail-desktop/assets/334996/50051ae2-e1fb-4a48-876f-e96d7c295e7c)
(from https://www.electronjs.org/docs/latest/api/browser-window#event-app-command-windows-linux)

Seems the only way to make it work on Mac is to add an explicit keyboard listener. 

I'll make a PR for this.
