### ISSUE TITLE
Notifications aren't working on Windows

### ISSUE THREAD

**Issue by DonaldDuck313** [timche/gmail-desktop#324]
**OS**
Windows 11

**Gmail Desktop Version**
2.25.3.0

**Describe the bug**
I'm not getting notifications on Windows.

**Steps to reproduce the behavior**

1. Open Gmail Desktop
2. Ask someone to send you an email
3. You won't get a notification

**Expected behavior**
I expect to get a notification whenever I get a new email.

**Additional context**
If I look at your [source code](https://github.com/timche/gmail-desktop/blob/main/src/notifications.ts), it looks like you use Electron notifications. According to the [documentation](https://www.electronjs.org/docs/latest/tutorial/notifications#windows),

> On Windows 10, a shortcut to your app with an [Application User Model ID](https://msdn.microsoft.com/en-us/library/windows/desktop/dd378459(v=vs.85).aspx) must be installed to the Start Menu.

(It doesn't say anything about Windows 11 so I assume that also applies to Windows 11.)

I don't know anything about Electron so I'm not sure how to fix this, but it would be nice if you could have Gmail Desktop somehow automatically add this shortcut with an Application User Model ID.

**Comment by timche** [comment]
Have you enabled [desktop notifications in Gmail](https://support.google.com/mail/answer/1075549?hl=en-GB&co=GENIE.Platform%3DDesktop)?

**Comment by DonaldDuck313** [comment]
> Have you enabled [desktop notifications in Gmail](https://support.google.com/mail/answer/1075549?hl=en-GB&co=GENIE.Platform%3DDesktop)?

Thanks, it worked. It's not clear from your documentation that I need to do that though, I assumed that it worked like the official Android app where notifications are on by default. Maybe you should clarify that in your documentation, [something like this](https://github.com/timche/gmail-desktop/pull/325).
