### ISSUE TITLE
Targeted debug mode

### ISSUE THREAD

**Issue by markypython** [timche/gmail-desktop#33]
It would be good to have debug mode only set for development or for specific users (i.e. you and me).  Perhaps reading from an environment variable?

Thoughts?

**Comment by timche** [comment]
I think it would be okay to make it a public option or is there anything sensitive in debug mode?

**Comment by markypython** [comment]
There isn't anything sensitive in debug mode, but it seems like something that shouldn't be turned on for the general public.  I could see a setting to enable debug mode that people can selected, but I probably wouldn't enable it by default for everyone.

**Comment by timche** [comment]
Yes, I actually meant a setting which is disabled by default.

**Comment by markypython** [comment]
Ah, I see.
