### ISSUE TITLE
Unable to see signin text in dark mode

### ISSUE THREAD

**Issue by twodayslate** [timche/gmail-desktop#334]
**OS**
macOS

**Gmail Desktop Version**
Version 2.25.3 (2.25.3)

**Describe the bug**

1. Enable dark mode
2. Attempt to signin

**Expected behavior**
You should be able to see what you are typing

**Media**
<img width="651" alt="Screen Shot 2022-07-21 at 12 03 02 AM" src="https://user-images.githubusercontent.com/1085707/180127589-0ee4299a-3c25-477d-a20b-23f708800857.png">

**Additional context**
n/a

**Comment by timche** [comment]
Fixed with 4c2401816bc24d5af1c4376975031b0048f1cf24
