### ISSUE TITLE
Icons Problem

### ISSUE THREAD

**Issue by albertberlanga** [timche/gmail-desktop#335]
**OS**
Windows

**Gmail Desktop Version**
3.0.0 Alpha 34

<img width="605" alt="04-08-2022_17-44-28" src="https://user-images.githubusercontent.com/65016698/182889731-ab062d1e-90b7-4085-8315-c3fd8e4c34a7.png">

Problem with some icons. They didn't load.

**Comment by timche** [comment]
Please use the old UI. We don't support the new UI yet.

**Comment by JohnLGalt** [comment]
Weird. I enabled the new view and the icons were working for a good while before they abruptly broke.  I suspect that Google changed the icons in the new UI to something different as a WiP for the new UI, eh?

**Comment by timche** [comment]
It looks okay for me. @JohnLGalt please give it 24-48 hours and check again after. I've the assumption that it's something server-side that's blocking the requests to load the icons.

<img width="665" alt="Screenshot 2022-08-10 at 20 32 17" src="https://user-images.githubusercontent.com/8075074/184004265-1866e308-78fc-4f93-8b2d-c74a02d4b3a1.png">

**Comment by JohnLGalt** [comment]
> 

No go - still getting the weird blocks instead of icons.

However, I also have a custom background that I've used for that Gmail account (in fact, all my accounts have different custom backgrounds). I'll do some playing around and see if I can narrow down the cause.
