### ISSUE TITLE
Black Theme issues while signing in.

### ISSUE THREAD

**Issue by Hershey025** [timche/gmail-desktop#357]
**OS**
Windows

**Gmail Desktop Version* 3.00 alpha 35*
You can find the version at `Gmail Desktop` → `About Gmail Desktop`. Make sure you're running the latest version to make sure the bug hasn't been fixed yet.

**Describe the bug**
Bug when we click on login the login page black theme is not consistent. Many areas are grey and white
![Screenshot (249)](https://user-images.githubusercontent.com/94620635/203975282-6eeaa345-aee0-4331-a0c3-67b249b791f1.png)

**Comment by JohnLGalt** [comment]
The latest alpha is 3.0.0-alpha.35 (dev). Is that what you meant?

**Comment by Hershey025** [comment]
> The latest alpha is 3.0.0-alpha.35 (dev). Is that what you meant?

Yes

**Comment by WebShapedBiz** [comment]
I can confirm that on Linux (elementaryOS 6.1, Ubuntu 20.04 based) this bug looks exactly the same.

**Comment by timche** [comment]
Fixed with 4c2401816bc24d5af1c4376975031b0048f1cf24
