### ISSUE TITLE
Mac menu bar icon

### ISSUE THREAD

**Issue by mskelton** [timche/gmail-desktop#36]
It would nice to have a menu bar icon showing the count of unread emails in the Mac menu bar.  I envision something like Todoist (see screenshot below).

![2019-03-12_21-52-44](https://user-images.githubusercontent.com/25914066/54250292-322bc280-4511-11e9-8708-60e26486c97f.png)

**Comment by timche** [comment]
I don't have a MB with touch bar, would be a cool addition though :) 👍

**Comment by markypython** [comment]
My apologies, I meant the menu bar at the top of the screen.

**Comment by timche** [comment]
Oh okay. I first thought of it, but I personally dislike it. I'd rather make it configurable and you can choose between dock, menu bar or dock + menu bar. What do you think?

**Comment by markypython** [comment]
I definitely like the idea of making it configurable.

**Comment by zzpxyx** [comment]
Do we have any plan on implementing this? I've done some quick experiments and it seems feasible?

**Comment by timche** [comment]
I'm not sure why I closed this issue, but contributions are very welcome adding this feature!

**Comment by zzpxyx** [comment]
No problem. I'm still learning here, but I'll see if I can come up with something. Thanks!
