### ISSUE TITLE
Couldn't sign you in (The browser app may not be secure)

### ISSUE THREAD

**Issue by hrqmonteiro** [timche/gmail-desktop#361]
**OS**
Linux (Fedora 37)

**Gmail Desktop Version**
3.0.0-alpha.35 (dev)

**Describe the bug**
Open the app -> try to log -> get this error

**Steps to reproduce the behavior**
Just said above

**Expected behavior**
To let me login?

**Media**

**Additional context**
![Screenshot from 2023-01-08 14-51-27](https://user-images.githubusercontent.com/17055027/211211252-dd312c95-bfe9-48d4-8086-139879bfc4d7.png)

**Comment by JohnLGalt** [comment]
Check to see if the `Use User Agent Fix` is enabled

`3 dot Menu --> Gmail Desktop --> Preferences --> User Agent --> Use User Agent Fix`

if enabled, try disabling. If disabled, try enabling.

**Comment by eshack94** [comment]
@JohnLGalt That worked for me. Thank you.
