### ISSUE TITLE
Re-logins constantly required but still no keychain support

### ISSUE THREAD

**Issue by patrickyan** [timche/gmail-desktop#365]
**OS**
macOS

**Gmail Desktop Version**
Version: 3.0.0-alpha.35 (dev)

**Describe the bug**
Google keeps asking for me to enter my password to confirm it's me, but there is no keychain support so I need to manually go find my password and copy paste it.

**Steps to reproduce the behavior**

1. Google asks for password.
2. Password field does not support keychain

**Expected behavior**
Clicking on the password field should pop open the keychain prompt for autofill passwords.

**Comment by timche** [comment]
Electron unfortunately doesn't support keychain and Google keep asking for your password is a safety measurement by Google.
