### ISSUE TITLE
Compact Header view - search input is not resized 

### ISSUE THREAD

**Issue by pedrodonkey** [timche/gmail-desktop#370]
**OS**
macOS - Ventura 13.4 (22F66)

**Gmail Desktop Version**
Version: 3.0.0-alpha.35 (dev)

**Describe the bug**
Compact Header view is broken in latest beta

**Steps to reproduce the behavior**

1. Go to View > Gmail Appearance 
2. Click on Compact Header to enable it
3. App will restart and you'll see the search input is not resized

**Expected behavior**
The search input in the header when Compact Header is enabled should be resized to fit

**Media**
<img width="790" alt="Screenshot 2023-06-13 at 2 07 41 PM" src="https://github.com/timche/gmail-desktop/assets/1678763/695fb85f-2cd3-4ec0-8e9d-6ec5df60e93b">

**Comment by pedrodonkey** [comment]
> Thanks for reporting this issue :) I'll fix it asap as I've just started a new job!

No worries @timche and thank you! All the best with your new job :)

**Comment by timche** [comment]
Fixed with ce27dcdc453480615fdca0c53dd231fc266bc118
