### ISSUE TITLE
Rebrand project

### ISSUE THREAD

**Issue by timche** [timche/gmail-desktop#39]
As we are using Gmail and it's logo, it can potentially happen that we are getting a legal notice as it could confuse people that it looks like an official app and we are asked to change the name and logo. In order to avoid these issues in advance, we could rename our app, but I'm no legal expert if we actually need to.

**Comment by bsramin** [comment]
Regardless of everything, I agree to use a custom name and icon, so as to add even a greater user experience for the project (eg also integrate google calendar and more ..)

**Comment by markypython** [comment]
@timche Thoughts on a new name/icon?

**Comment by timche** [comment]
Don't have made up my mind yet, but there were projects in the past which have given away free open source logos:
- https://github.com/arasatasaygin/openlogos
- There is another one which I can't find right now

I'm not a designer (anymore), but there is also this site with quite a few free logos: http://logodust.com/

Based on the logo we could come up with a name.

**Comment by timche** [comment]
Name ideas:

- Inbox (not that Inbox is dead :D)
- Loop (Keeping in the loop)
- Columba (Latin for dove)
- Avem (Latin for bird)
- Mailbox
- Loopbox
- Postal

Here are a few logos that I like from http://logodust.com/:

![image](https://user-images.githubusercontent.com/8075074/56084220-d1511c00-5e27-11e9-8dac-47f9b65e9026.png)

![image](https://user-images.githubusercontent.com/8075074/56084223-dca44780-5e27-11e9-8b6d-96890bca0512.png)

![image](https://user-images.githubusercontent.com/8075074/56084224-e3cb5580-5e27-11e9-8de0-39d9c1170c37.png)

![image](https://user-images.githubusercontent.com/8075074/56084226-eded5400-5e27-11e9-89b4-d1352ab82b97.png)

![image](https://user-images.githubusercontent.com/8075074/56084227-f5146200-5e27-11e9-89bb-25e5976ec655.png)

**Comment by timche** [comment]
@markypython any thoughts on the ideas? 😄

**Comment by markypython** [comment]
Thoughts on each logo:

1. I like this logo best of all.  Not sure why, but it just looks good.
1. I don't quite understand how this one fits with our app, interested to hear why you liked this one.
1. Second favorite.  Seems like it could look really cool with some alternating colors, but might be a little strange as a dock icon (maybe?)
1. Looks to much like Matco tools to me
    ![Matco tools](https://assets.entrepreneur.com/franchise/avatar/282564.jpg)
1. Same thought as 2

**Comment by markypython** [comment]
Thoughts on the names:

- Inbox - probably too confusing since Inbox was a thing
- Loop - Not sure about the loop idea.  Just doesn't jive with me
- Columba - Like the idea of going somewhat abstract, but I'm not a huge fan of how Columba rolls of the tongue
- Avem - Same thought as Columba
- Mailbox - Seems a bit to generic
- Loopbox - Same thought as Loop
- Postal - Okay, but if anything I would want to go with Postman, except for the fact that that is taken :)

**Comment by markypython** [comment]
Sorry for the tough feedback, but I wanted to share what I was feeling.  Thanks for looking into this and putting together some ideas, naming things is really hard!

**Comment by timche** [comment]
Thanks for your feedback! That was just quick brainstorming by me, so no worries for the tough feedback ;)

---

**Logos**

So potential logos are:

![image](https://user-images.githubusercontent.com/8075074/56288946-baf0dc00-6117-11e9-9c90-65be4f04a19e.png)

![image](https://user-images.githubusercontent.com/8075074/56288951-bdebcc80-6117-11e9-85d7-31b74a9de3b7.png)

I don't see no. 5 fitting into the mail application context anymore, so I'll exclude this.

-- 

**Name**

I agree that an abstract name would be good, but we need more ideas.

**Comment by markypython** [comment]
Here are some other name ideas.

- Pony Express (the second logo in your most recent comment would go well)
- Mailbag (not sure which logo to use for this one)
- Courier (would work with the c shaped logo)

**Comment by cipriancraciun** [comment]
@markypython `Courier` is the name of a (former?) mail server:  https://en.wikipedia.org/wiki/Courier_Mail_Server

---

Just for fun:  why not call it `GeMail`?  (I.e. `GMail` with `Electron`?)  :)  (Although it makes a poor Google Search candidate...)

That being said, I would suggest that whatever name is chosen it should be quite "unique" on Google Search (i.e. searching for it on Google shouldn't respond with Google owned pages in the first few pages), otherwise it would be quite hard to find (about) it...  (For that reason I started naming my projects by randomly generating their names, and double checking that on Google Search;  for example `vonuvoli` and `kawipiko`, two of my latest pet-projects.)

BTW, if you choose a name that represents something in another language, I used to play with Icelandic (by using Google Translate), as it sounds quite nice (sometimes), almost like Latin, and there aren't many icelandic-native pages to clutter Google Search.  Just to prove a point, the word `postur` is the translation for `mail`;  obviously the mail company in Iceland is called `Postur`, however searching for `GPostur` on Google Search, although it returns something, the pages have almost nothing in common with that word, therefore this project would pop-up as the first result in a couple of weeks.

**Comment by timche** [comment]
I really like the name **Courier** and the C shaped logo fits perfectly for it. Also there doesn't seem to be another app called "Courier".

**Comment by markypython** [comment]
@cipriancraciun I think there is a fine line between an abstract name and a name that is too abstract.

**Comment by markypython** [comment]
@timche If we go forward with Courier and use the c shaped logo, I was thinking that it would probably look good if we use the colors from the gmail logo as the background and foreground.  So, the c would be colored Gmail red on a white background.  That and adding a border radius to it would make it work pretty nice.

I would envision it looking something like the quicken logo (shown below) but with inverted colors and a different letter (the c logo in our case).

![Quicken](https://banner2.kisspng.com/20180520/cb/kisspng-quicken-logo-intuit-netflix-quickbooks-5b0199996bce83.7383703015268315134416.jpg)

Thoughts?

**Comment by timche** [comment]
I have tried to play around with the "C" shaped logo, but I don't really like anymore:

![Frame](https://user-images.githubusercontent.com/8075074/56437096-17015f00-62d6-11e9-86ee-614364345b1a.png)

I also tried out the other logo we considered and I think looks way better:

![Frame2](https://user-images.githubusercontent.com/8075074/56437787-a576e000-62d8-11e9-8bb2-39596bec7dc6.png)

**Comment by markypython** [comment]
As far as the logo, when seeing them side-by-side in color, I agree that the second one looks better.  As far as the name, I'm not a fan of misspelled names for brands.  I think a well thought name is much better than a misspelled name.

**Comment by timche** [comment]
What do you think of [Bearer](https://www.thesaurus.com/browse/bearer)?

**Comment by markypython** [comment]
Bearer doesn't click well with me.  If you want to abandon courier, I'm fine with that as it wasn't my top choice anyway.  I'll do some more thinking 😄

**Comment by timche** [comment]
I'd just like to explore alternatives which might be fancier 😄

**Comment by markypython** [comment]
Okay, I wasn't thinking fancy but I will now 👍

**Comment by markypython** [comment]
Just found [this video](https://www.youtube.com/watch?time_continue=129&v=wAUO5kFFPIg) on the internet about creating a good name.  It has some good thoughts about what to consider when creating a name.

Thought I should share it while we are talking about names!

**Comment by cipriancraciun** [comment]
@markypython (Just saying) Have you tried a "code name" generator like:
* http://www.codenamegenerator.com/
* https://mrsharpoblunto.github.io/foswig.js/
* (some other found on Google?  in fact even the ones above were find on Google;)

Perhaps it will spark an idea after iterating through some of the suggestions.

**Comment by markypython** [comment]
@cipriancraciun I tried some different name generators which certainly helped just to think of different names, but nothing stuck out that I really liked.  The only two I thought were interesting were Mailr (yes, I did mention I don't like misspelled names, but this one seems different for some reason) and Reply Rocket.

Here are a couple sites I used:

- https://namelix.com
- https://www.brandbucket.com/search?q=mail

**Comment by timche** [comment]
I was thinking about a name which fits better to the second logo. What do you think of these:
- Mailee
- Mailray
- Mailtron

I'd like to have a name with a single word.

**Comment by markypython** [comment]
I like mailtron, but it looks like it is already used for an email related application.

http://www.studiotron.com/mailtrongateway/

**Comment by timche** [comment]
> I like mailtron, but it looks like it is already used for an email related application.
> 
> http://www.studiotron.com/mailtrongateway/

It doesn't look very active anymore. Last release was 2006: http://www.studiotron.com/mailtrongateway/release/releasenotes_mt.html

Also the full name is "Mailtron Gateway".

Is that still an issue?

**Comment by markypython** [comment]
Fair point.  It probably doesn't matter at this point then.

**Comment by timche** [comment]
I also tried a different variation of the logo:

![Rectangle 2](https://user-images.githubusercontent.com/8075074/56732554-15b0b600-675e-11e9-8130-e1c21f67fd03.png)

**Comment by markypython** [comment]
Personally, I like the other logo better with the off-white background and the red color for the inner portion.

**Comment by timche** [comment]
What do you think of this?

![Frame](https://user-images.githubusercontent.com/8075074/56732730-8f48a400-675e-11e9-8fcd-9df4deea9508.png)

---

It's more of a "flat style".

**Comment by markypython** [comment]
Either is fine with me.  I like different aspects of both :)

**Comment by timche** [comment]
I made the gray background a little less "dirty":

![Frame](https://user-images.githubusercontent.com/8075074/56732989-26adf700-675f-11e9-9107-3709fabeb228.png)

**Comment by timche** [comment]
I also adjusted the gaps between the "lines" so they are the same space and the top left line was actually vertically misaligned.

![Frame](https://user-images.githubusercontent.com/8075074/56733110-83a9ad00-675f-11e9-9f35-7ac7f0d3bb47.png)

**Comment by timche** [comment]
I like that it kinda looks like a paperclip/attachment in an email.
