### ISSUE TITLE
Questioning CHANGELOG.md

### ISSUE THREAD

**Issue by timche** [timche/gmail-desktop#49]
Since writing the changes in CHANGELOG.md, I feel like I'm doing more work than necessary to make releases and document changes. Before I'd just create a new GitHub release and write down the changes in the release notes, which I think is more convenient and I can still do changes anytime unlike with the changelog file.

@markypython would you mind if we are writing the changelogs only in the releases again?

**Comment by markypython** [comment]
Sure.  I thought it would be a good idea to try it and see how it went, but I would agree that it has been more difficult to manage.

**Comment by timche** [comment]
@markypython Let us still use the [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) style to write changelogs in releases.
