### ISSUE TITLE
Mac "traffic lights" overlap content in new windows

### ISSUE THREAD

**Issue by markypython** [timche/gmail-desktop#50]
When opening a new window or a notification, the Mac "traffic lights" overlap the content.

- Gmail Desktop Version: 2.4.0
- OS Version: macOS Mojave

Steps to Reproduce:

1. Hold down command/ctrl and click the compose button
2. Observe how the Mac "traffic lights" overlap the content

![2019-04-09_06-52-31](https://user-images.githubusercontent.com/25914066/55798249-1bd34100-5a94-11e9-9a83-456e26605a09.png)

**Comment by markypython** [comment]
Related to #42

**Comment by bsramin** [comment]
I try to take a look at it

**Comment by markypython** [comment]
@bsramin I started working on it already, so let me get my branch I'm working on published so you can help from there.

**Comment by markypython** [comment]
I uploaded my branch named `fix-new-window-header`.  You can compare it with master [here](https://github.com/timche/gmail-desktop/compare/fix-new-window-header).

As I mentioned, there seems to be an issue in electron that is causing this related to preload scripts (css falls into the same category).  https://github.com/electron/electron/issues/16224

**Comment by markypython** [comment]
@timche Are you good with downgrading electron to 3.0.4 until this issue is resolved on their end?  It doesn't break anything to downgrade and I doubt we would be needing electron 4+ features before this issue is resolved.

**Comment by timche** [comment]
> Are you good with downgrading electron to 3.0.4 

Sure.

**Comment by markypython** [comment]
@bsramin Do you still wan't to tackle this using my branch as a starter?

**Comment by markypython** [comment]
I think part of the fix for this PR ought to be disabling ctrl/cmd click on elements to prevent them from being opened in a new window.  That would limit the screens that need updates to the PDF viewer and the email viewer when clicking on notifications.

**Comment by timche** [comment]
Question: Why do we want to add the custom CSS in the new created windows? Doesn't the CSS only modify the main page? So if we would remove [these lines](https://github.com/timche/gmail-desktop/blob/master/src/app.ts#L176-L178) and set [`options.titleBarStyle: 'default` here](https://github.com/timche/gmail-desktop/blob/master/src/app.ts#L175), wouldn't it solve this issue? Because I don't see a reason why new created windows should have no titlebar as we would need to fix all possible windows so the traffic lights look good. Just wondering.

**Comment by markypython** [comment]
We could do that, but as far as I can tell, the styles I added should cover all the cases where a new window will open.  The pdf viewer styles are required for the main window, so the only two other cases are the new compose window and the email view from the notification click.

**Comment by timche** [comment]
What if we are excluding them by checking the url?

**Comment by markypython** [comment]
Could you explain that question?  I think I might know what you are talking about, but I'm not sure.

**Comment by timche** [comment]
So for compose and email view windows, we could not inject our custom CSS and set the `titleBarStyle` to `default`, by checking the new created window url.

**Comment by markypython** [comment]
If you don't want to inject the custom css for the compose or email view windows, then we would just turn off hiddenInset for new windows like you mentioned above.  The reason I would like to add the styles to those windows is it makes them cleaner and less cluttered (which helps since they are small windows when they open by default) and it also matches with the style of the main window really well.

We have some additional work to do make all non mail|accounts.google.com urls use `shell.openExternal` when a link is clicked on from inside the new window that is opened.  Aside from that issue which will be fixed at some point soon (I'll open an issue), I don't think there are any other cases that would require the custom css.  In my testing, I went through and ctrl clicked on lots of different elements to see what they would do and only the email view and compose button opened in a new window.  Most other elements just opened as they normally would.

**Comment by timche** [comment]
> to add the styles to those windows is it makes them cleaner and less cluttered (which helps since they are small windows when they open by default) and it also matches with the style of the main window really well

That's a fair point. Well, then I'm up for it 👍 Thanks for clarifying.
