### ISSUE TITLE
Move to travis-ci.com for builds

### ISSUE THREAD

**Issue by markypython** [timche/gmail-desktop#56]
Travis is migrating from the old .org domain to the new .com domain.  We should move this repo to the .com domain to stay up to date and prevent issues down the road when they will likely turn off .org.

**Resources**

- https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps
- https://devops.stackexchange.com/questions/1201/whats-the-difference-between-travis-ci-org-and-travis-ci-com

**Comment by timche** [comment]
This is already on my list for all my repos that are still on Travis.org. The migration is still in beta and not accessible for everyone the last time I checked. Will take a look at it again.

**Comment by timche** [comment]
Once travis-ci.com migration is out of beta, I'll move the repo, but as this is a task for all my repositories, this doesn't need to be tracked.
