### ISSUE TITLE
Close window on click "Archive" when email opened in new window

### ISSUE THREAD

**Issue by timche** [timche/gmail-desktop#62]
When opening an email via an notification, the email will be opened in a new window. It would be nice when clicking on "Archive" the window will be closed automatically. This is a behaviour I know from the Gmail app on iOS.

This could be made configurable.

**Comment by markypython** [comment]
Same behavior when you click delete as well

**Comment by timche** [comment]
There is also a "Report spam" button, could be the same behaviour.
