### ISSUE TITLE
Show offline banner when internet is not available

### ISSUE THREAD

**Issue by timche** [timche/gmail-desktop#71]
Show an offline banner for example on top of the window to let the user know that he is offline using [is-online](https://www.npmjs.com/package/is-online).

**Comment by markypython** [comment]
I like the idea, but I wonder if this would conflict with the existing gmail offline indicator.

![2019-04-13_13-23-04](https://user-images.githubusercontent.com/25914066/56083783-4ce2a700-5def-11e9-8abd-63aad400a4b0.png)

**Comment by timche** [comment]
Oh, I forgot about that one. We could instead wait for this element to appear, make it prettier and put it as full width banner on top/bottom.
