### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by timche** [timche/gmail-desktop#75]
Not sure if this is easy to maintain in case the CSS selectors are changing frequently, but I'm a fan of dark themes as it's easier for the eyes. Also the theme colors needs to be defined. Could look into a possible color scheme.

Inspired by: https://github.com/sindresorhus/caprine#dark-mode

Related to #23.

**Comment by markypython** [comment]
@timche Should we close this in favor of Gmail's built in dark theme?
