### ISSUE TITLE
Use electron-store instead of electron-settings

### ISSUE THREAD

**Issue by timche** [timche/gmail-desktop#80]
Differences:
- TypeScript support
- [Set defaults](https://github.com/sindresorhus/electron-store#defaults)
- [Define schema](https://github.com/sindresorhus/electron-store#schema)
- Can be easily used in main and renderer process

**Comment by markypython** [comment]
This would probably be good to put in a file that we then export some helper functions from.  This would make it easier in the future to swap out storage libraries if necessary.

**Comment by timche** [comment]
> This would make it easier in the future to swap out storage libraries if necessary.

From my experience, it's way easier to refactor and safer with TS in case we are swapping libraries. Anyway, most storage libraries have similar APIs.
