### ISSUE TITLE
Compose window created by "mailto" is unstyled (macOS) and blank after sending

### ISSUE THREAD

**Issue by timche** [timche/gmail-desktop#85]
- Gmail Desktop Version: 2.6.1
- OS Version: macOS Mojave

Steps to Reproduce:

1. Open a [`mailto:foo@example.com`](mailto:foo@example.com) link
2. Compose window should open with `foo@example.com` as recipient
3. macOS: Notice how the title bar is the standard system title bar and unstyled
4. After clicking on `send`, the window is completely blank with a small notification on the bottom left with `Message sent`

**Comment by timche** [comment]
Most probably the window that get's created probably has a slightly different url that isn't detected by our [regex](https://github.com/timche/gmail-desktop/blob/master/src/app.ts#L179).

CC @markypython

**Comment by markypython** [comment]
@timche The next 2 weeks are quite busy for me, so I'm not sure how much time I'll be able to spend helping with these issues.  I'll make sure and finish the issue I have a PR for and then help wherever else I can, but I unfortunately will not be as available as I was last week!

Thanks for opening this though.  I think we should take a look at this after the other window header PR is finished up.

**Comment by timche** [comment]
v3.0.0 is opening `mailto` links in the main window.
