### ISSUE TITLE
`this._state.bounds` can be undefined and crashes the app

### ISSUE THREAD

**Issue by timche** [timche/gmail-desktop#86]
![image](https://user-images.githubusercontent.com/8075074/56137499-e72c2180-5f8c-11e9-80ea-06e6a78e5486.png)

- Gmail Desktop Version: 2.6.1
- OS Version: Windows 10

Steps to Reproduce:

Not clear how to reproduce exactly, but the error can be reproduced programmatically:

```diff
diff --git a/src/state/window.ts b/src/state/window.ts
index a80809d..e20ddf9 100644
--- a/src/state/window.ts
+++ b/src/state/window.ts
@@ -49,6 +49,7 @@ export default class WindowState {
     } else if (this._state.isMaximized) {
       this._window.maximize()
     } else {
+      delete this._state.bounds
       this._window.setBounds(this._state.bounds!)
     }
   }
```

This happened to me only on Windows (once), but I think this can happen on all OS. It's not safe to use `this._window.setBounds(this._state.bounds!)` when `this._state.bounds` is not defined.

**Possible solution:**
Define window state default

```ts
{
  isMaximized: true,
  isFullscreen: false,
  bounds: {
    width: 800,
    height: 600,
    // Center the window
    y: undefined as unknown as number,
    x: undefined as unknown as number
  }
}
```

**Comment by markypython** [comment]
@timche The logic in `window.ts` is setup to handle all the cases where window state is set, unset, partially set, etc.  I see where you are going with your test case, but it isn't really valid as you won't get to that portion of the code without window bounds.

🤷‍♂️

**Comment by timche** [comment]
Well, as I said, I don't how how to reproduce it, but somehow it still happened and I wasn't able to get rid of the error until deleted the saved window state.

**Comment by timche** [comment]
Anyway, as I was looking into `window.ts` again, I was wondering if we couldn't just save the window state only on `app.on('before-quit')` and not on the `'resize', 'move', 'close'` window events.

I noticed that moving the window doesn't look smooth (Windows 10), so I started the app without `WindowState` and moving was smooth again.

**Comment by markypython** [comment]
I like the idea of trying `app.on('before-quit')`.  Also, I guess we could just add an `else if (this._state.bounds)` and then be assured we won't ever have an issue.

**Comment by JimTim** [comment]
I getting the same error.
