### ISSUE TITLE
Change menu in Windows and Linux

### ISSUE THREAD

**Issue by cipriancraciun** [timche/gmail-desktop#88]
For some reason the window menu-bar (i.e. the one containing `Gmail Desktop`, `Settings`, etc.) is visible all the time, and there is no option to hide it.

(I don't know if this is by design, or an issue with my window manager, namely `i3`.  I'm using OpenSUSE Tumbleweed, and manually installed the `2.6.1` from the Debian `.deb` by extracting it into a custom folder.)

**Comment by timche** [comment]
Can you provide a screenshot please?

**Comment by cipriancraciun** [comment]
The following is the upper-left corner of my root window:

![image](https://user-images.githubusercontent.com/29785/56283895-a282c080-611b-11e9-9429-154d892128d1.png)

**Comment by markypython** [comment]
If the window is hidden, how would you access settings?

**Comment by timche** [comment]
Offtopic: How did you manage to invert the colors?

**Comment by cipriancraciun** [comment]
For example in Slack when I press (and release) `Alt` the window menu-bar becomes visible.  (I think this is built-in in Electron, as I've seen this behavior in many other applications.)

**Comment by cipriancraciun** [comment]
> Offtopic: How did you manage to invert the colors?

I just use the `Dark` theme from the Gmail `Theme` settings.

**Comment by timche** [comment]
Interesting, didn't know it exists, thanks for sharing!

(Relates to #75)

**Comment by timche** [comment]
Currently the menu bar in Windows looks similar like on Linux.

I already thought earlier about changing it to something like in other apps:

**Slack**
![image](https://user-images.githubusercontent.com/8075074/56284401-42385280-610c-11e9-9797-6eaf910eff18.png)

**VSCode**
![image](https://user-images.githubusercontent.com/8075074/56284430-567c4f80-610c-11e9-8cba-9209401f4f58.png)

**Hyper**

**Comment by timche** [comment]
I'll change this issue to change the title/menu bar on Windows & Linux.

CC @markypython

**Comment by markypython** [comment]
Sounds good to me!
