### ISSUE TITLE
Option to configure the font size (or at least zoom)

### ISSUE THREAD

**Issue by cipriancraciun** [timche/gmail-desktop#89]
(At least in my case) the default font size is too small for me to easily read the emails.

It would be nice to have an option to customize the font (at least size, but family would also be helpful).

Additionally a zoom option would also be helpful.

**Comment by timche** [comment]
Thanks for the suggestion!

**Comment by cipriancraciun** [comment]
OK, apparently now that we have custom styles one can "hack" this by adding the following to their "custom styles" file (located in `~/.config/GMail Desktop/custom.css`:

```
html:root {
    zoom : 1.5;
}
```

Apparently the "recommended" way suggested by Mozilla:
* https://developer.mozilla.org/en-US/docs/Web/CSS/@viewport/zoom
* https://developer.mozilla.org/en-US/docs/Web/CSS/@viewport

, doesn't seem to work...
