### ISSUE TITLE
Add support for RPM packages (for Linux)

### ISSUE THREAD

**Issue by cipriancraciun** [timche/gmail-desktop#91]
I've seen that on the release tab there already is `.deb`, and from what I gathered it is generated by some generic tool you have integrated.  Could you also add support for `.rpm`?

**Comment by timche** [comment]
We are using `electron-builder` and `.rpm` is supported: https://www.electron.build/configuration/linux#LinuxConfiguration-target

**Comment by timche** [comment]
I'm taking [Caprine](https://github.com/sindresorhus/caprine) as an inspiration for this project and it additionally provides their app as snap and something with `pacman`. Are these somehow useful for you? I'd like to go with the most popular ones and don't build every single possible target.

**Comment by cipriancraciun** [comment]
`pacman` is the ArchLinux package manager, therefore I would say it is useful to include it also.

I would also include `snap` (similar to `AppImage`), but also `tar.bz2`.  The last one is for those whose package manager is not on the list.

(By the same reasoning I would also include `zip` on Windows builds.)

**Comment by timche** [comment]
So do we still require `.rpm` when we are providing the others?

**Comment by cipriancraciun** [comment]
> So do we still require `.rpm` when we are providing the others?

Yes.

To summarize:
* `.deb` for Debian / Ubuntu based Linux distributions;
* `.rpm` for Fedora / OpenSUSE / CentOS based distributions;
* `pacman` (the extension is I believe `.tar.xz`, but it contains some extra files) for ArchLinux;
* `.AppImage` / `.snap` (and Flatpak if supported) for DMG-like installs on Linux;  (in this regard this topic is still in "flux" in the Linux world);
* `.tar.bz2` for those Linux users that have other distributions (not based on one of the above), or whose package manager fails (for some reason) to ingest one of the package formats above;

**Comment by cipriancraciun** [comment]
Although if you want to minimize the number of files, I would say `.deb`, `.rpm` and `.tar.bz2` is the minimal recommended set.

**Comment by cipriancraciun** [comment]
@timche Did something happen to the linux `.tar.bz2` release bundle?

(When I installed 2.6.1 it was an option, but now I see it disappeared for that version also...)

**Comment by cyfrost** [comment]
Hi,
I have a fork of this project that is modified to suit my personal workflows, [here's the repo](https://github.com/cyfrost/gmail-electron). There are a few things that are different with the fork (one of which is relevant to this thread). I've added more build targets (.rpm, .pacman, .snap) to the existing set. Please let me know If you'd be interested in a PR (it is a very small change indeed).

**Comment by timche** [comment]
Hi @cyfrost, you are more than welcome to propose changes and contribute to this project in order to improve it. Our goal is to support every platform as good as possible, but since @markypython and I are primarily using macOS, we definitely need more support for Linux and Windows.

**Comment by cyfrost** [comment]
@timche Sounds great, I primarily use Linux (Fedora) for all things, and sometimes Windows. So I can help with issues related to these platforms.

Please take a look at my fork and the [things that are different](https://github.com/cyfrost/gmail-electron#differences-from-upstream-project) with it and let me know if you want to cherry-pick some of them.
