### ISSUE TITLE
Make "Silent auto-updates" optional

### ISSUE THREAD

**Issue by cipriancraciun** [timche/gmail-desktop#92]
First of all I understand that auto-update is extremely useful for 99% of the users (especially non-technical ones).  However in this day-and-age, especially for the security-conscious user, auto-update also implies that the tool you are using is downloading new code behind your back...  (This is why I consider it as a "bug" and not a "feature" request.)

Therefore I would strongly suggest to make this "silent auto-update" an optional feature, perhaps "opt-out" (i.e. enabled by default, but allowing one to disable it if needed).

Moreover I don't know how this auto-update would work on Linux where the package is installed in system-managed folders, and changing the installed files would require `root` access.

**Comment by timche** [comment]
Per the `electron-builder` docs, it says that auto-updates is only supported for `AppImage`: https://www.electron.build/auto-update#auto-updatable-targets

But I agree that silent auto-update can be a little too intrusive. I was thinking to go back to notify the user about a new available update and to ask them to "download and install" it.

@markypython thoughts?

**Comment by timche** [comment]
@allcontributors[bot] add @cipriancraciun for ideas
