### ISSUE TITLE
Do not use spaces in the install folder name for Linux

### ISSUE THREAD

**Issue by cipriancraciun** [timche/gmail-desktop#94]
At the moment the generated `.deb` package installs this application under `/opt/Gmail Desktop/...`, which includes a space in the folder name.

Now although all of the Linux file-systems, and the package management tools, do support files with spaces in their names, it is considered bad practice, especially since it interacts poorly with `sh` scripts that correctly fail to quote their arguments.

I would suggest stripping the space.

(Unfortunately at the moment I can't find any official document forbidding the use of spaces, just Google `linux path space` and you'll find countless posts tackling issues stemming from this cause.)

**Comment by markypython** [comment]
Depending on what we choose for the new name for this app, this may be fixed when we rebrand.

Related to #39

**Comment by markypython** [comment]
@timche Do we still plan to fix this or are we still going to rebrand the project?

**Comment by timche** [comment]
I don't we are rebranding it but instead could simply omit `Desktop`, what do you think?

**Comment by markypython** [comment]
Not sure I understand.  Do you mean calling the app Gmail?

**Comment by timche** [comment]
> Not sure I understand. Do you mean calling the app Gmail?

Correct

**Comment by markypython** [comment]
Wouldn't that make it worse from a legal standpoint?

**Comment by timche** [comment]
I'm no lawyer, but Gmail is a trademark. So I think in general using this name isn't legal anyway, but it's totally up to Google to request us to not use the name. There has been a similar case by sindresorhus where he got a [legal notice](https://github.com/sindresorhus/legal-notices/blob/master/2015-12-12-github.md).

**Comment by markypython** [comment]
The other problem I could see with calling it simply Gmail is that it would increase confusion about if it is an official or unofficial desktop client as well as make it harder for people to find the application as they would constantly be finding gmail.com in search results rather than this project.

Those are some of my other reasons why I would think it could be risky to call it just Gmail.

**Comment by timche** [comment]
Will be resolved with v3 when we rename the project.
