### ISSUE TITLE
Add support for opening multiple inbox windows

### ISSUE THREAD

**Issue by cipriancraciun** [timche/gmail-desktop#95]
At times, especially when working on multiple tasks at once, it would be helpful to be able to open multiple inbox windows at the same time.

Therefore a nice new option would be to add a `New` option under the `Window` menu, perhaps triggered by the `Ctrl+N` shortcut, to open a new inbox window.

**Comment by cipriancraciun** [comment]
This is related to #72, however it implies more than quick access in the same window.

**Comment by alainsr** [comment]
Alternative request: allow multiple instances to run simultaneously. Not ideal in terms of RAM, but could be a short term workaround.

**Comment by cipriancraciun** [comment]
Any updates on this item?  (As with #90, this is the only reason I still have to use sometimes GMail from a browser.)

**Comment by timche** [comment]
It's part of v3 #177, but due to a rendering bug in Electron, the development is paused. I'll revisit this asap.

**Comment by timche** [comment]
Will be obsolete with #25
